//
//  SettingXmlParserNewSetting.swift
//  microcosm-mac
//
//  Created by Yuji Ogata on 2016/11/15.
//  Copyright © 2016年 Yuji Ogata. All rights reserved.
//

import Cocoa

class SettingXmlParserNewSetting: NSObject {
    let xmlhead: String = "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
    let xmltop: String = "<SettingXml xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">"
    let xmlend: String = "</SettingXml>"
    
    let dispnameStart: String = "  <dispname>"
    let dispnameEnd: String = "</dispname>"
    let orbSunSoft1st0Start: String = "  <orb_sun_soft_1st_0>"
    let orbSunSoft1st0End: String = "</orb_sun_soft_1st_0>"
    let orbSunSoft1st1Start: String = "  <orb_sun_soft_1st_1>"
    let orbSunSoft1st1End: String = "</orb_sun_soft_1st_1>"
    let orbSunSoft1st2Start: String = "  <orb_sun_soft_1st_2>"
    let orbSunSoft1st2End: String = "</orb_sun_soft_1st_2>"
    let orbSunSoft1st3Start: String = "  <orb_sun_soft_1st_3>"
    let orbSunSoft1st3End: String = "</orb_sun_soft_1st_3>"
    let orbSunSoft1st4Start: String = "  <orb_sun_soft_1st_4>"
    let orbSunSoft1st4End: String = "</orb_sun_soft_1st_4>"
    let orbSunSoft1st5Start: String = "  <orb_sun_soft_1st_5>"
    let orbSunSoft1st5End: String = "</orb_sun_soft_1st_5>"
    let orbSunHard1st0Start: String = "  <orb_sun_hard_1st_0>"
    let orbSunHard1st0End: String = "</orb_sun_hard_1st_0>"
    let orbSunHard1st1Start: String = "  <orb_sun_hard_1st_1>"
    let orbSunHard1st1End: String = "</orb_sun_hard_1st_1>"
    let orbSunHard1st2Start: String = "  <orb_sun_hard_1st_2>"
    let orbSunHard1st2End: String = "</orb_sun_hard_1st_2>"
    let orbSunHard1st3Start: String = "  <orb_sun_hard_1st_3>"
    let orbSunHard1st3End: String = "</orb_sun_hard_1st_3>"
    let orbSunHard1st4Start: String = "  <orb_sun_hard_1st_4>"
    let orbSunHard1st4End: String = "</orb_sun_hard_1st_4>"
    let orbSunHard1st5Start: String = "  <orb_sun_hard_1st_5>"
    let orbSunHard1st5End: String = "</orb_sun_hard_1st_5>"
    let orbMoonSoft1st0Start: String = "  <orb_moon_soft_1st_0>"
    let orbMoonSoft1st0End: String = "</orb_moon_soft_1st_0>"
    let orbMoonSoft1st1Start: String = "  <orb_moon_soft_1st_1>"
    let orbMoonSoft1st1End: String = "</orb_moon_soft_1st_1>"
    let orbMoonSoft1st2Start: String = "  <orb_moon_soft_1st_2>"
    let orbMoonSoft1st2End: String = "</orb_moon_soft_1st_2>"
    let orbMoonSoft1st3Start: String = "  <orb_moon_soft_1st_3>"
    let orbMoonSoft1st3End: String = "</orb_moon_soft_1st_3>"
    let orbMoonSoft1st4Start: String = "  <orb_moon_soft_1st_4>"
    let orbMoonSoft1st4End: String = "</orb_moon_soft_1st_4>"
    let orbMoonSoft1st5Start: String = "  <orb_moon_soft_1st_5>"
    let orbMoonSoft1st5End: String = "</orb_moon_soft_1st_5>"
    let orbMoonHard1st0Start: String = "  <orb_moon_hard_1st_0>"
    let orbMoonHard1st0End: String = "</orb_moon_hard_1st_0>"
    let orbMoonHard1st1Start: String = "  <orb_moon_hard_1st_1>"
    let orbMoonHard1st1End: String = "</orb_moon_hard_1st_1>"
    let orbMoonHard1st2Start: String = "  <orb_moon_hard_1st_2>"
    let orbMoonHard1st2End: String = "</orb_moon_hard_1st_2>"
    let orbMoonHard1st3Start: String = "  <orb_moon_hard_1st_3>"
    let orbMoonHard1st3End: String = "</orb_moon_hard_1st_3>"
    let orbMoonHard1st4Start: String = "  <orb_moon_hard_1st_4>"
    let orbMoonHard1st4End: String = "</orb_moon_hard_1st_4>"
    let orbMoonHard1st5Start: String = "  <orb_moon_hard_1st_5>"
    let orbMoonHard1st5End: String = "</orb_moon_hard_1st_5>"
    let orbOtherSoft1st0Start: String = "  <orb_other_soft_1st_0>"
    let orbOtherSoft1st0End: String = "</orb_other_soft_1st_0>"
    let orbOtherSoft1st1Start: String = "  <orb_other_soft_1st_1>"
    let orbOtherSoft1st1End: String = "</orb_other_soft_1st_1>"
    let orbOtherSoft1st2Start: String = "  <orb_other_soft_1st_2>"
    let orbOtherSoft1st2End: String = "</orb_other_soft_1st_2>"
    let orbOtherSoft1st3Start: String = "  <orb_other_soft_1st_3>"
    let orbOtherSoft1st3End: String = "</orb_other_soft_1st_3>"
    let orbOtherSoft1st4Start: String = "  <orb_other_soft_1st_4>"
    let orbOtherSoft1st4End: String = "</orb_other_soft_1st_4>"
    let orbOtherSoft1st5Start: String = "  <orb_other_soft_1st_5>"
    let orbOtherSoft1st5End: String = "</orb_other_soft_1st_5>"
    let orbOtherHard1st0Start: String = "  <orb_other_hard_1st_0>"
    let orbOtherHard1st0End: String = "</orb_other_hard_1st_0>"
    let orbOtherHard1st1Start: String = "  <orb_other_hard_1st_1>"
    let orbOtherHard1st1End: String = "</orb_other_hard_1st_1>"
    let orbOtherHard1st2Start: String = "  <orb_other_hard_1st_2>"
    let orbOtherHard1st2End: String = "</orb_other_hard_1st_2>"
    let orbOtherHard1st3Start: String = "  <orb_other_hard_1st_3>"
    let orbOtherHard1st3End: String = "</orb_other_hard_1st_3>"
    let orbOtherHard1st4Start: String = "  <orb_other_hard_1st_4>"
    let orbOtherHard1st4End: String = "</orb_other_hard_1st_4>"
    let orbOtherHard1st5Start: String = "  <orb_other_hard_1st_5>"
    let orbOtherHard1st5End: String = "</orb_other_hard_1st_5>"
    let orbSunSoft2nd0Start: String = "  <orb_sun_soft_2nd_0>"
    let orbSunSoft2nd0End: String = "</orb_sun_soft_2nd_0>"
    let orbSunSoft2nd1Start: String = "  <orb_sun_soft_2nd_1>"
    let orbSunSoft2nd1End: String = "</orb_sun_soft_2nd_1>"
    let orbSunSoft2nd2Start: String = "  <orb_sun_soft_2nd_2>"
    let orbSunSoft2nd2End: String = "</orb_sun_soft_2nd_2>"
    let orbSunSoft2nd3Start: String = "  <orb_sun_soft_2nd_3>"
    let orbSunSoft2nd3End: String = "</orb_sun_soft_2nd_3>"
    let orbSunSoft2nd4Start: String = "  <orb_sun_soft_2nd_4>"
    let orbSunSoft2nd4End: String = "</orb_sun_soft_2nd_4>"
    let orbSunSoft2nd5Start: String = "  <orb_sun_soft_2nd_5>"
    let orbSunSoft2nd5End: String = "</orb_sun_soft_2nd_5>"
    let orbSunHard2nd0Start: String = "  <orb_sun_hard_2nd_0>"
    let orbSunHard2nd0End: String = "</orb_sun_hard_2nd_0>"
    let orbSunHard2nd1Start: String = "  <orb_sun_hard_2nd_1>"
    let orbSunHard2nd1End: String = "</orb_sun_hard_2nd_1>"
    let orbSunHard2nd2Start: String = "  <orb_sun_hard_2nd_2>"
    let orbSunHard2nd2End: String = "</orb_sun_hard_2nd_2>"
    let orbSunHard2nd3Start: String = "  <orb_sun_hard_2nd_3>"
    let orbSunHard2nd3End: String = "</orb_sun_hard_2nd_3>"
    let orbSunHard2nd4Start: String = "  <orb_sun_hard_2nd_4>"
    let orbSunHard2nd4End: String = "</orb_sun_hard_2nd_4>"
    let orbSunHard2nd5Start: String = "  <orb_sun_hard_2nd_5>"
    let orbSunHard2nd5End: String = "</orb_sun_hard_2nd_5>"
    let orbMoonSoft2nd0Start: String = "  <orb_moon_soft_2nd_0>"
    let orbMoonSoft2nd0End: String = "</orb_moon_soft_2nd_0>"
    let orbMoonSoft2nd1Start: String = "  <orb_moon_soft_2nd_1>"
    let orbMoonSoft2nd1End: String = "</orb_moon_soft_2nd_1>"
    let orbMoonSoft2nd2Start: String = "  <orb_moon_soft_2nd_2>"
    let orbMoonSoft2nd2End: String = "</orb_moon_soft_2nd_2>"
    let orbMoonSoft2nd3Start: String = "  <orb_moon_soft_2nd_3>"
    let orbMoonSoft2nd3End: String = "</orb_moon_soft_2nd_3>"
    let orbMoonSoft2nd4Start: String = "  <orb_moon_soft_2nd_4>"
    let orbMoonSoft2nd4End: String = "</orb_moon_soft_2nd_4>"
    let orbMoonSoft2nd5Start: String = "  <orb_moon_soft_2nd_5>"
    let orbMoonSoft2nd5End: String = "</orb_moon_soft_2nd_5>"
    let orbMoonHard2nd0Start: String = "  <orb_moon_hard_2nd_0>"
    let orbMoonHard2nd0End: String = "</orb_moon_hard_2nd_0>"
    let orbMoonHard2nd1Start: String = "  <orb_moon_hard_2nd_1>"
    let orbMoonHard2nd1End: String = "</orb_moon_hard_2nd_1>"
    let orbMoonHard2nd2Start: String = "  <orb_moon_hard_2nd_2>"
    let orbMoonHard2nd2End: String = "</orb_moon_hard_2nd_2>"
    let orbMoonHard2nd3Start: String = "  <orb_moon_hard_2nd_3>"
    let orbMoonHard2nd3End: String = "</orb_moon_hard_2nd_3>"
    let orbMoonHard2nd4Start: String = "  <orb_moon_hard_2nd_4>"
    let orbMoonHard2nd4End: String = "</orb_moon_hard_2nd_4>"
    let orbMoonHard2nd5Start: String = "  <orb_moon_hard_2nd_5>"
    let orbMoonHard2nd5End: String = "</orb_moon_hard_2nd_5>"
    let orbOtherSoft2nd0Start: String = "  <orb_other_soft_2nd_0>"
    let orbOtherSoft2nd0End: String = "</orb_other_soft_2nd_0>"
    let orbOtherSoft2nd1Start: String = "  <orb_other_soft_2nd_1>"
    let orbOtherSoft2nd1End: String = "</orb_other_soft_2nd_1>"
    let orbOtherSoft2nd2Start: String = "  <orb_other_soft_2nd_2>"
    let orbOtherSoft2nd2End: String = "</orb_other_soft_2nd_2>"
    let orbOtherSoft2nd3Start: String = "  <orb_other_soft_2nd_3>"
    let orbOtherSoft2nd3End: String = "</orb_other_soft_2nd_3>"
    let orbOtherSoft2nd4Start: String = "  <orb_other_soft_2nd_4>"
    let orbOtherSoft2nd4End: String = "</orb_other_soft_2nd_4>"
    let orbOtherSoft2nd5Start: String = "  <orb_other_soft_2nd_5>"
    let orbOtherSoft2nd5End: String = "</orb_other_soft_2nd_5>"
    let orbOtherHard2nd0Start: String = "  <orb_other_hard_2nd_0>"
    let orbOtherHard2nd0End: String = "</orb_other_hard_2nd_0>"
    let orbOtherHard2nd1Start: String = "  <orb_other_hard_2nd_1>"
    let orbOtherHard2nd1End: String = "</orb_other_hard_2nd_1>"
    let orbOtherHard2nd2Start: String = "  <orb_other_hard_2nd_2>"
    let orbOtherHard2nd2End: String = "</orb_other_hard_2nd_2>"
    let orbOtherHard2nd3Start: String = "  <orb_other_hard_2nd_3>"
    let orbOtherHard2nd3End: String = "</orb_other_hard_2nd_3>"
    let orbOtherHard2nd4Start: String = "  <orb_other_hard_2nd_4>"
    let orbOtherHard2nd4End: String = "</orb_other_hard_2nd_4>"
    let orbOtherHard2nd5Start: String = "  <orb_other_hard_2nd_5>"
    let orbOtherHard2nd5End: String = "</orb_other_hard_2nd_5>"
    let orbSunSoft1500Start: String = "  <orb_sun_soft_150_0>"
    let orbSunSoft1500End: String = "</orb_sun_soft_150_0>"
    let orbSunSoft1501Start: String = "  <orb_sun_soft_150_1>"
    let orbSunSoft1501End: String = "</orb_sun_soft_150_1>"
    let orbSunSoft1502Start: String = "  <orb_sun_soft_150_2>"
    let orbSunSoft1502End: String = "</orb_sun_soft_150_2>"
    let orbSunSoft1503Start: String = "  <orb_sun_soft_150_3>"
    let orbSunSoft1503End: String = "</orb_sun_soft_150_3>"
    let orbSunSoft1504Start: String = "  <orb_sun_soft_150_4>"
    let orbSunSoft1504End: String = "</orb_sun_soft_150_4>"
    let orbSunSoft1505Start: String = "  <orb_sun_soft_150_5>"
    let orbSunSoft1505End: String = "</orb_sun_soft_150_5>"
    let orbSunHard1500Start: String = "  <orb_sun_hard_150_0>"
    let orbSunHard1500End: String = "</orb_sun_hard_150_0>"
    let orbSunHard1501Start: String = "  <orb_sun_hard_150_1>"
    let orbSunHard1501End: String = "</orb_sun_hard_150_1>"
    let orbSunHard1502Start: String = "  <orb_sun_hard_150_2>"
    let orbSunHard1502End: String = "</orb_sun_hard_150_2>"
    let orbSunHard1503Start: String = "  <orb_sun_hard_150_3>"
    let orbSunHard1503End: String = "</orb_sun_hard_150_3>"
    let orbSunHard1504Start: String = "  <orb_sun_hard_150_4>"
    let orbSunHard1504End: String = "</orb_sun_hard_150_4>"
    let orbSunHard1505Start: String = "  <orb_sun_hard_150_5>"
    let orbSunHard1505End: String = "</orb_sun_hard_150_5>"
    let orbMoonSoft1500Start: String = "  <orb_moon_soft_150_0>"
    let orbMoonSoft1500End: String = "</orb_moon_soft_150_0>"
    let orbMoonSoft1501Start: String = "  <orb_moon_soft_150_1>"
    let orbMoonSoft1501End: String = "</orb_moon_soft_150_1>"
    let orbMoonSoft1502Start: String = "  <orb_moon_soft_150_2>"
    let orbMoonSoft1502End: String = "</orb_moon_soft_150_2>"
    let orbMoonSoft1503Start: String = "  <orb_moon_soft_150_3>"
    let orbMoonSoft1503End: String = "</orb_moon_soft_150_3>"
    let orbMoonSoft1504Start: String = "  <orb_moon_soft_150_4>"
    let orbMoonSoft1504End: String = "</orb_moon_soft_150_4>"
    let orbMoonSoft1505Start: String = "  <orb_moon_soft_150_5>"
    let orbMoonSoft1505End: String = "</orb_moon_soft_150_5>"
    let orbMoonHard1500Start: String = "  <orb_moon_hard_150_0>"
    let orbMoonHard1500End: String = "</orb_moon_hard_150_0>"
    let orbMoonHard1501Start: String = "  <orb_moon_hard_150_1>"
    let orbMoonHard1501End: String = "</orb_moon_hard_150_1>"
    let orbMoonHard1502Start: String = "  <orb_moon_hard_150_2>"
    let orbMoonHard1502End: String = "</orb_moon_hard_150_2>"
    let orbMoonHard1503Start: String = "  <orb_moon_hard_150_3>"
    let orbMoonHard1503End: String = "</orb_moon_hard_150_3>"
    let orbMoonHard1504Start: String = "  <orb_moon_hard_150_4>"
    let orbMoonHard1504End: String = "</orb_moon_hard_150_4>"
    let orbMoonHard1505Start: String = "  <orb_moon_hard_150_5>"
    let orbMoonHard1505End: String = "</orb_moon_hard_150_5>"
    let orbOtherSoft1500Start: String = "  <orb_other_soft_150_0>"
    let orbOtherSoft1500End: String = "</orb_other_soft_150_0>"
    let orbOtherSoft1501Start: String = "  <orb_other_soft_150_1>"
    let orbOtherSoft1501End: String = "</orb_other_soft_150_1>"
    let orbOtherSoft1502Start: String = "  <orb_other_soft_150_2>"
    let orbOtherSoft1502End: String = "</orb_other_soft_150_2>"
    let orbOtherSoft1503Start: String = "  <orb_other_soft_150_3>"
    let orbOtherSoft1503End: String = "</orb_other_soft_150_3>"
    let orbOtherSoft1504Start: String = "  <orb_other_soft_150_4>"
    let orbOtherSoft1504End: String = "</orb_other_soft_150_4>"
    let orbOtherSoft1505Start: String = "  <orb_other_soft_150_5>"
    let orbOtherSoft1505End: String = "</orb_other_soft_150_5>"
    let orbOtherHard1500Start: String = "  <orb_other_hard_150_0>"
    let orbOtherHard1500End: String = "</orb_other_hard_150_0>"
    let orbOtherHard1501Start: String = "  <orb_other_hard_150_1>"
    let orbOtherHard1501End: String = "</orb_other_hard_150_1>"
    let orbOtherHard1502Start: String = "  <orb_other_hard_150_2>"
    let orbOtherHard1502End: String = "</orb_other_hard_150_2>"
    let orbOtherHard1503Start: String = "  <orb_other_hard_150_3>"
    let orbOtherHard1503End: String = "</orb_other_hard_150_3>"
    let orbOtherHard1504Start: String = "  <orb_other_hard_150_4>"
    let orbOtherHard1504End: String = "</orb_other_hard_150_4>"
    let orbOtherHard1505Start: String = "  <orb_other_hard_150_5>"
    let orbOtherHard1505End: String = "</orb_other_hard_150_5>"
    let dispcircle0Start: String = "  <dispcircle>"
    let dispcircle0End: String = "</dispcircle>"
    let dispcircle1Start: String = "  <dispcircle>"
    let dispcircle1End: String = "</dispcircle>"
    let dispcircle2Start: String = "  <dispcircle>"
    let dispcircle2End: String = "</dispcircle>"
    let dispcircle3Start: String = "  <dispcircle>"
    let dispcircle3End: String = "</dispcircle>"
    let dispcircle4Start: String = "  <dispcircle>"
    let dispcircle4End: String = "</dispcircle>"
    let dispcircle5Start: String = "  <dispcircle>"
    let dispcircle5End: String = "</dispcircle>"
    let dispplanetSun11Start: String = "  <dispPlanetSun11>"
    let dispplanetSun11End: String = "</dispPlanetSun11>"
    let dispplanetMoon11Start: String = "  <dispPlanetMoon11>"
    let dispplanetMoon11End: String = "</dispPlanetMoon11>"
    let dispplanetMercury11Start: String = "  <dispPlanetMercury11>"
    let dispplanetMercury11End: String = "</dispPlanetMercury11>"
    let dispplanetVenus11Start: String = "  <dispPlanetVenus11>"
    let dispplanetVenus11End: String = "</dispPlanetVenus11>"
    let dispplanetMars11Start: String = "  <dispPlanetMars11>"
    let dispplanetMars11End: String = "</dispPlanetMars11>"
    let dispplanetJupiter11Start: String = "  <dispPlanetJupiter11>"
    let dispplanetJupiter11End: String = "</dispPlanetJupiter11>"
    let dispplanetSaturn11Start: String = "  <dispPlanetSaturn11>"
    let dispplanetSaturn11End: String = "</dispPlanetSaturn11>"
    let dispplanetUranus11Start: String = "  <dispPlanetUranus11>"
    let dispplanetUranus11End: String = "</dispPlanetUranus11>"
    let dispplanetNeptune11Start: String = "  <dispPlanetNeptune11>"
    let dispplanetNeptune11End: String = "</dispPlanetNeptune11>"
    let dispplanetPluto11Start: String = "  <dispPlanetPluto11>"
    let dispplanetPluto11End: String = "</dispPlanetPluto11>"
    let dispplanetDh11Start: String = "  <dispPlanetDh11>"
    let dispplanetDh11End: String = "</dispPlanetDh11>"
    let dispplanetChiron11Start: String = "  <dispPlanetChiron11>"
    let dispplanetChiron11End: String = "</dispPlanetChiron11>"
    let dispplanetAsc11Start: String = "  <dispPlanetAsc11>"
    let dispplanetAsc11End: String = "</dispPlanetAsc11>"
    let dispplanetMc11Start: String = "  <dispPlanetMc11>"
    let dispplanetMc11End: String = "</dispPlanetMc11>"
    let dispplanetEarth11Start: String = "  <dispPlanetEarth11>"
    let dispplanetEarth11End: String = "</dispPlanetEarth11>"
    let dispplanetLilith11Start: String = "  <dispPlanetLilith11>"
    let dispplanetLilith11End: String = "</dispPlanetLilith11>"
    let dispplanetSun22Start: String = "  <dispPlanetSun22>"
    let dispplanetSun22End: String = "</dispPlanetSun22>"
    let dispplanetMoon22Start: String = "  <dispPlanetMoon22>"
    let dispplanetMoon22End: String = "</dispPlanetMoon22>"
    let dispplanetMercury22Start: String = "  <dispPlanetMercury22>"
    let dispplanetMercury22End: String = "</dispPlanetMercury22>"
    let dispplanetVenus22Start: String = "  <dispPlanetVenus22>"
    let dispplanetVenus22End: String = "</dispPlanetVenus22>"
    let dispplanetMars22Start: String = "  <dispPlanetMars22>"
    let dispplanetMars22End: String = "</dispPlanetMars22>"
    let dispplanetJupiter22Start: String = "  <dispPlanetJupiter22>"
    let dispplanetJupiter22End: String = "</dispPlanetJupiter22>"
    let dispplanetSaturn22Start: String = "  <dispPlanetSaturn22>"
    let dispplanetSaturn22End: String = "</dispPlanetSaturn22>"
    let dispplanetUranus22Start: String = "  <dispPlanetUranus22>"
    let dispplanetUranus22End: String = "</dispPlanetUranus22>"
    let dispplanetNeptune22Start: String = "  <dispPlanetNeptune22>"
    let dispplanetNeptune22End: String = "</dispPlanetNeptune22>"
    let dispplanetPluto22Start: String = "  <dispPlanetPluto22>"
    let dispplanetPluto22End: String = "</dispPlanetPluto22>"
    let dispplanetDh22Start: String = "  <dispPlanetDh22>"
    let dispplanetDh22End: String = "</dispPlanetDh22>"
    let dispplanetChiron22Start: String = "  <dispPlanetChiron22>"
    let dispplanetChiron22End: String = "</dispPlanetChiron22>"
    let dispplanetAsc22Start: String = "  <dispPlanetAsc22>"
    let dispplanetAsc22End: String = "</dispPlanetAsc22>"
    let dispplanetMc22Start: String = "  <dispPlanetMc22>"
    let dispplanetMc22End: String = "</dispPlanetMc22>"
    let dispplanetEarth22Start: String = "  <dispPlanetEarth22>"
    let dispplanetEarth22End: String = "</dispPlanetEarth22>"
    let dispplanetLilith22Start: String = "  <dispPlanetLilith22>"
    let dispplanetLilith22End: String = "</dispPlanetLilith22>"
    let dispplanetSun33Start: String = "  <dispPlanetSun33>"
    let dispplanetSun33End: String = "</dispPlanetSun33>"
    let dispplanetMoon33Start: String = "  <dispPlanetMoon33>"
    let dispplanetMoon33End: String = "</dispPlanetMoon33>"
    let dispplanetMercury33Start: String = "  <dispPlanetMercury33>"
    let dispplanetMercury33End: String = "</dispPlanetMercury33>"
    let dispplanetVenus33Start: String = "  <dispPlanetVenus33>"
    let dispplanetVenus33End: String = "</dispPlanetVenus33>"
    let dispplanetMars33Start: String = "  <dispPlanetMars33>"
    let dispplanetMars33End: String = "</dispPlanetMars33>"
    let dispplanetJupiter33Start: String = "  <dispPlanetJupiter33>"
    let dispplanetJupiter33End: String = "</dispPlanetJupiter33>"
    let dispplanetSaturn33Start: String = "  <dispPlanetSaturn33>"
    let dispplanetSaturn33End: String = "</dispPlanetSaturn33>"
    let dispplanetUranus33Start: String = "  <dispPlanetUranus33>"
    let dispplanetUranus33End: String = "</dispPlanetUranus33>"
    let dispplanetNeptune33Start: String = "  <dispPlanetNeptune33>"
    let dispplanetNeptune33End: String = "</dispPlanetNeptune33>"
    let dispplanetPluto33Start: String = "  <dispPlanetPluto33>"
    let dispplanetPluto33End: String = "</dispPlanetPluto33>"
    let dispplanetDh33Start: String = "  <dispPlanetDh33>"
    let dispplanetDh33End: String = "</dispPlanetDh33>"
    let dispplanetChiron33Start: String = "  <dispPlanetChiron33>"
    let dispplanetChiron33End: String = "</dispPlanetChiron33>"
    let dispplanetAsc33Start: String = "  <dispPlanetAsc33>"
    let dispplanetAsc33End: String = "</dispPlanetAsc33>"
    let dispplanetMc33Start: String = "  <dispPlanetMc33>"
    let dispplanetMc33End: String = "</dispPlanetMc33>"
    let dispplanetEarth33Start: String = "  <dispPlanetEarth33>"
    let dispplanetEarth33End: String = "</dispPlanetEarth33>"
    let dispplanetLilith33Start: String = "  <dispPlanetLilith33>"
    let dispplanetLilith33End: String = "</dispPlanetLilith33>"
    let dispplanetSun12Start: String = "  <dispPlanetSun12>"
    let dispplanetSun12End: String = "</dispPlanetSun12>"
    let dispplanetMoon12Start: String = "  <dispPlanetMoon12>"
    let dispplanetMoon12End: String = "</dispPlanetMoon12>"
    let dispplanetMercury12Start: String = "  <dispPlanetMercury12>"
    let dispplanetMercury12End: String = "</dispPlanetMercury12>"
    let dispplanetVenus12Start: String = "  <dispPlanetVenus12>"
    let dispplanetVenus12End: String = "</dispPlanetVenus12>"
    let dispplanetMars12Start: String = "  <dispPlanetMars12>"
    let dispplanetMars12End: String = "</dispPlanetMars12>"
    let dispplanetJupiter12Start: String = "  <dispPlanetJupiter12>"
    let dispplanetJupiter12End: String = "</dispPlanetJupiter12>"
    let dispplanetSaturn12Start: String = "  <dispPlanetSaturn12>"
    let dispplanetSaturn12End: String = "</dispPlanetSaturn12>"
    let dispplanetUranus12Start: String = "  <dispPlanetUranus12>"
    let dispplanetUranus12End: String = "</dispPlanetUranus12>"
    let dispplanetNeptune12Start: String = "  <dispPlanetNeptune12>"
    let dispplanetNeptune12End: String = "</dispPlanetNeptune12>"
    let dispplanetPluto12Start: String = "  <dispPlanetPluto12>"
    let dispplanetPluto12End: String = "</dispPlanetPluto12>"
    let dispplanetDh12Start: String = "  <dispPlanetDh12>"
    let dispplanetDh12End: String = "</dispPlanetDh12>"
    let dispplanetChiron12Start: String = "  <dispPlanetChiron12>"
    let dispplanetChiron12End: String = "</dispPlanetChiron12>"
    let dispplanetAsc12Start: String = "  <dispPlanetAsc12>"
    let dispplanetAsc12End: String = "</dispPlanetAsc12>"
    let dispplanetMc12Start: String = "  <dispPlanetMc12>"
    let dispplanetMc12End: String = "</dispPlanetMc12>"
    let dispplanetEarth12Start: String = "  <dispPlanetEarth12>"
    let dispplanetEarth12End: String = "</dispPlanetEarth12>"
    let dispplanetLilith12Start: String = "  <dispPlanetLilith12>"
    let dispplanetLilith12End: String = "</dispPlanetLilith12>"
    let dispplanetSun13Start: String = "  <dispPlanetSun13>"
    let dispplanetSun13End: String = "</dispPlanetSun13>"
    let dispplanetMoon13Start: String = "  <dispPlanetMoon13>"
    let dispplanetMoon13End: String = "</dispPlanetMoon13>"
    let dispplanetMercury13Start: String = "  <dispPlanetMercury13>"
    let dispplanetMercury13End: String = "</dispPlanetMercury13>"
    let dispplanetVenus13Start: String = "  <dispPlanetVenus13>"
    let dispplanetVenus13End: String = "</dispPlanetVenus13>"
    let dispplanetMars13Start: String = "  <dispPlanetMars13>"
    let dispplanetMars13End: String = "</dispPlanetMars13>"
    let dispplanetJupiter13Start: String = "  <dispPlanetJupiter13>"
    let dispplanetJupiter13End: String = "</dispPlanetJupiter13>"
    let dispplanetSaturn13Start: String = "  <dispPlanetSaturn13>"
    let dispplanetSaturn13End: String = "</dispPlanetSaturn13>"
    let dispplanetUranus13Start: String = "  <dispPlanetUranus13>"
    let dispplanetUranus13End: String = "</dispPlanetUranus13>"
    let dispplanetNeptune13Start: String = "  <dispPlanetNeptune13>"
    let dispplanetNeptune13End: String = "</dispPlanetNeptune13>"
    let dispplanetPluto13Start: String = "  <dispPlanetPluto13>"
    let dispplanetPluto13End: String = "</dispPlanetPluto13>"
    let dispplanetDh13Start: String = "  <dispPlanetDh13>"
    let dispplanetDh13End: String = "</dispPlanetDh13>"
    let dispplanetChiron13Start: String = "  <dispPlanetChiron13>"
    let dispplanetChiron13End: String = "</dispPlanetChiron13>"
    let dispplanetAsc13Start: String = "  <dispPlanetAsc13>"
    let dispplanetAsc13End: String = "</dispPlanetAsc13>"
    let dispplanetMc13Start: String = "  <dispPlanetMc13>"
    let dispplanetMc13End: String = "</dispPlanetMc13>"
    let dispplanetEarth13Start: String = "  <dispPlanetEarth13>"
    let dispplanetEarth13End: String = "</dispPlanetEarth13>"
    let dispplanetLilith13Start: String = "  <dispPlanetLilith13>"
    let dispplanetLilith13End: String = "</dispPlanetLilith13>"
    let dispplanetSun23Start: String = "  <dispPlanetSun23>"
    let dispplanetSun23End: String = "</dispPlanetSun23>"
    let dispplanetMoon23Start: String = "  <dispPlanetMoon23>"
    let dispplanetMoon23End: String = "</dispPlanetMoon23>"
    let dispplanetMercury23Start: String = "  <dispPlanetMercury23>"
    let dispplanetMercury23End: String = "</dispPlanetMercury23>"
    let dispplanetVenus23Start: String = "  <dispPlanetVenus23>"
    let dispplanetVenus23End: String = "</dispPlanetVenus23>"
    let dispplanetMars23Start: String = "  <dispPlanetMars23>"
    let dispplanetMars23End: String = "</dispPlanetMars23>"
    let dispplanetJupiter23Start: String = "  <dispPlanetJupiter23>"
    let dispplanetJupiter23End: String = "</dispPlanetJupiter23>"
    let dispplanetSaturn23Start: String = "  <dispPlanetSaturn23>"
    let dispplanetSaturn23End: String = "</dispPlanetSaturn23>"
    let dispplanetUranus23Start: String = "  <dispPlanetUranus23>"
    let dispplanetUranus23End: String = "</dispPlanetUranus23>"
    let dispplanetNeptune23Start: String = "  <dispPlanetNeptune23>"
    let dispplanetNeptune23End: String = "</dispPlanetNeptune23>"
    let dispplanetPluto23Start: String = "  <dispPlanetPluto23>"
    let dispplanetPluto23End: String = "</dispPlanetPluto23>"
    let dispplanetDh23Start: String = "  <dispPlanetDh23>"
    let dispplanetDh23End: String = "</dispPlanetDh23>"
    let dispplanetChiron23Start: String = "  <dispPlanetChiron23>"
    let dispplanetChiron23End: String = "</dispPlanetChiron23>"
    let dispplanetAsc23Start: String = "  <dispPlanetAsc23>"
    let dispplanetAsc23End: String = "</dispPlanetAsc23>"
    let dispplanetMc23Start: String = "  <dispPlanetMc23>"
    let dispplanetMc23End: String = "</dispPlanetMc23>"
    let dispplanetEarth23Start: String = "  <dispPlanetEarth23>"
    let dispplanetEarth23End: String = "</dispPlanetEarth23>"
    let dispplanetLilith23Start: String = "  <dispPlanetLilith23>"
    let dispplanetLilith23End: String = "</dispPlanetLilith23>"
    let dispaspect0Start: String = "  <dispAspect>"
    let dispaspect0End: String = "</dispAspect>"
    let dispaspect1Start: String = "  <dispAspect>"
    let dispaspect1End: String = "</dispAspect>"
    let dispaspect2Start: String = "  <dispAspect>"
    let dispaspect2End: String = "</dispAspect>"
    let dispaspect3Start: String = "  <dispAspect>"
    let dispaspect3End: String = "</dispAspect>"
    let dispaspect4Start: String = "  <dispAspect>"
    let dispaspect4End: String = "</dispAspect>"
    let dispaspect5Start: String = "  <dispAspect>"
    let dispaspect5End: String = "</dispAspect>"
    let aspectSun11Start: String = "  <aspectSun11>"
    let aspectSun11End: String = "</aspectSun11>"
    let aspectMoon11Start: String = "  <aspectMoon11>"
    let aspectMoon11End: String = "</aspectMoon11>"
    let aspectMercury11Start: String = "  <aspectMercury11>"
    let aspectMercury11End: String = "</aspectMercury11>"
    let aspectVenus11Start: String = "  <aspectVenus11>"
    let aspectVenus11End: String = "</aspectVenus11>"
    let aspectMars11Start: String = "  <aspectMars11>"
    let aspectMars11End: String = "</aspectMars11>"
    let aspectJupiter11Start: String = "  <aspectJupiter11>"
    let aspectJupiter11End: String = "</aspectJupiter11>"
    let aspectSaturn11Start: String = "  <aspectSaturn11>"
    let aspectSaturn11End: String = "</aspectSaturn11>"
    let aspectUranus11Start: String = "  <aspectUranus11>"
    let aspectUranus11End: String = "</aspectUranus11>"
    let aspectNeptune11Start: String = "  <aspectNeptune11>"
    let aspectNeptune11End: String = "</aspectNeptune11>"
    let aspectPluto11Start: String = "  <aspectPluto11>"
    let aspectPluto11End: String = "</aspectPluto11>"
    let aspectDh11Start: String = "  <aspectDh11>"
    let aspectDh11End: String = "</aspectDh11>"
    let aspectChiron11Start: String = "  <aspectChiron11>"
    let aspectChiron11End: String = "</aspectChiron11>"
    let aspectAsc11Start: String = "  <aspectAsc11>"
    let aspectAsc11End: String = "</aspectAsc11>"
    let aspectMc11Start: String = "  <aspectMc11>"
    let aspectMc11End: String = "</aspectMc11>"
    let aspectEarth11Start: String = "  <aspectEarth11>"
    let aspectEarth11End: String = "</aspectEarth11>"
    let aspectLilith11Start: String = "  <aspectLilith11>"
    let aspectLilith11End: String = "</aspectLilith11>"
    let aspectSun22Start: String = "  <aspectSun22>"
    let aspectSun22End: String = "</aspectSun22>"
    let aspectMoon22Start: String = "  <aspectMoon22>"
    let aspectMoon22End: String = "</aspectMoon22>"
    let aspectMercury22Start: String = "  <aspectMercury22>"
    let aspectMercury22End: String = "</aspectMercury22>"
    let aspectVenus22Start: String = "  <aspectVenus22>"
    let aspectVenus22End: String = "</aspectVenus22>"
    let aspectMars22Start: String = "  <aspectMars22>"
    let aspectMars22End: String = "</aspectMars22>"
    let aspectJupiter22Start: String = "  <aspectJupiter22>"
    let aspectJupiter22End: String = "</aspectJupiter22>"
    let aspectSaturn22Start: String = "  <aspectSaturn22>"
    let aspectSaturn22End: String = "</aspectSaturn22>"
    let aspectUranus22Start: String = "  <aspectUranus22>"
    let aspectUranus22End: String = "</aspectUranus22>"
    let aspectNeptune22Start: String = "  <aspectNeptune22>"
    let aspectNeptune22End: String = "</aspectNeptune22>"
    let aspectPluto22Start: String = "  <aspectPluto22>"
    let aspectPluto22End: String = "</aspectPluto22>"
    let aspectDh22Start: String = "  <aspectDh22>"
    let aspectDh22End: String = "</aspectDh22>"
    let aspectChiron22Start: String = "  <aspectChiron22>"
    let aspectChiron22End: String = "</aspectChiron22>"
    let aspectAsc22Start: String = "  <aspectAsc22>"
    let aspectAsc22End: String = "</aspectAsc22>"
    let aspectMc22Start: String = "  <aspectMc22>"
    let aspectMc22End: String = "</aspectMc22>"
    let aspectEarth22Start: String = "  <aspectEarth22>"
    let aspectEarth22End: String = "</aspectEarth22>"
    let aspectLilith22Start: String = "  <aspectLilith22>"
    let aspectLilith22End: String = "</aspectLilith22>"
    let aspectSun33Start: String = "  <aspectSun33>"
    let aspectSun33End: String = "</aspectSun33>"
    let aspectMoon33Start: String = "  <aspectMoon33>"
    let aspectMoon33End: String = "</aspectMoon33>"
    let aspectMercury33Start: String = "  <aspectMercury33>"
    let aspectMercury33End: String = "</aspectMercury33>"
    let aspectVenus33Start: String = "  <aspectVenus33>"
    let aspectVenus33End: String = "</aspectVenus33>"
    let aspectMars33Start: String = "  <aspectMars33>"
    let aspectMars33End: String = "</aspectMars33>"
    let aspectJupiter33Start: String = "  <aspectJupiter33>"
    let aspectJupiter33End: String = "</aspectJupiter33>"
    let aspectSaturn33Start: String = "  <aspectSaturn33>"
    let aspectSaturn33End: String = "</aspectSaturn33>"
    let aspectUranus33Start: String = "  <aspectUranus33>"
    let aspectUranus33End: String = "</aspectUranus33>"
    let aspectNeptune33Start: String = "  <aspectNeptune33>"
    let aspectNeptune33End: String = "</aspectNeptune33>"
    let aspectPluto33Start: String = "  <aspectPluto33>"
    let aspectPluto33End: String = "</aspectPluto33>"
    let aspectDh33Start: String = "  <aspectDh33>"
    let aspectDh33End: String = "</aspectDh33>"
    let aspectChiron33Start: String = "  <aspectChiron33>"
    let aspectChiron33End: String = "</aspectChiron33>"
    let aspectAsc33Start: String = "  <aspectAsc33>"
    let aspectAsc33End: String = "</aspectAsc33>"
    let aspectMc33Start: String = "  <aspectMc33>"
    let aspectMc33End: String = "</aspectMc33>"
    let aspectEarth33Start: String = "  <aspectEarth33>"
    let aspectEarth33End: String = "</aspectEarth33>"
    let aspectLilith33Start: String = "  <aspectLilith33>"
    let aspectLilith33End: String = "</aspectLilith33>"
    let aspectSun12Start: String = "  <aspectSun12>"
    let aspectSun12End: String = "</aspectSun12>"
    let aspectMoon12Start: String = "  <aspectMoon12>"
    let aspectMoon12End: String = "</aspectMoon12>"
    let aspectMercury12Start: String = "  <aspectMercury12>"
    let aspectMercury12End: String = "</aspectMercury12>"
    let aspectVenus12Start: String = "  <aspectVenus12>"
    let aspectVenus12End: String = "</aspectVenus12>"
    let aspectMars12Start: String = "  <aspectMars12>"
    let aspectMars12End: String = "</aspectMars12>"
    let aspectJupiter12Start: String = "  <aspectJupiter12>"
    let aspectJupiter12End: String = "</aspectJupiter12>"
    let aspectSaturn12Start: String = "  <aspectSaturn12>"
    let aspectSaturn12End: String = "</aspectSaturn12>"
    let aspectUranus12Start: String = "  <aspectUranus12>"
    let aspectUranus12End: String = "</aspectUranus12>"
    let aspectNeptune12Start: String = "  <aspectNeptune12>"
    let aspectNeptune12End: String = "</aspectNeptune12>"
    let aspectPluto12Start: String = "  <aspectPluto12>"
    let aspectPluto12End: String = "</aspectPluto12>"
    let aspectDh12Start: String = "  <aspectDh12>"
    let aspectDh12End: String = "</aspectDh12>"
    let aspectChiron12Start: String = "  <aspectChiron12>"
    let aspectChiron12End: String = "</aspectChiron12>"
    let aspectAsc12Start: String = "  <aspectAsc12>"
    let aspectAsc12End: String = "</aspectAsc12>"
    let aspectMc12Start: String = "  <aspectMc12>"
    let aspectMc12End: String = "</aspectMc12>"
    let aspectEarth12Start: String = "  <aspectEarth12>"
    let aspectEarth12End: String = "</aspectEarth12>"
    let aspectLilith12Start: String = "  <aspectLilith12>"
    let aspectLilith12End: String = "</aspectLilith12>"
    let aspectSun13Start: String = "  <aspectSun13>"
    let aspectSun13End: String = "</aspectSun13>"
    let aspectMoon13Start: String = "  <aspectMoon13>"
    let aspectMoon13End: String = "</aspectMoon13>"
    let aspectMercury13Start: String = "  <aspectMercury13>"
    let aspectMercury13End: String = "</aspectMercury13>"
    let aspectVenus13Start: String = "  <aspectVenus13>"
    let aspectVenus13End: String = "</aspectVenus13>"
    let aspectMars13Start: String = "  <aspectMars13>"
    let aspectMars13End: String = "</aspectMars13>"
    let aspectJupiter13Start: String = "  <aspectJupiter13>"
    let aspectJupiter13End: String = "</aspectJupiter13>"
    let aspectSaturn13Start: String = "  <aspectSaturn13>"
    let aspectSaturn13End: String = "</aspectSaturn13>"
    let aspectUranus13Start: String = "  <aspectUranus13>"
    let aspectUranus13End: String = "</aspectUranus13>"
    let aspectNeptune13Start: String = "  <aspectNeptune13>"
    let aspectNeptune13End: String = "</aspectNeptune13>"
    let aspectPluto13Start: String = "  <aspectPluto13>"
    let aspectPluto13End: String = "</aspectPluto13>"
    let aspectDh13Start: String = "  <aspectDh13>"
    let aspectDh13End: String = "</aspectDh13>"
    let aspectChiron13Start: String = "  <aspectChiron13>"
    let aspectChiron13End: String = "</aspectChiron13>"
    let aspectAsc13Start: String = "  <aspectAsc13>"
    let aspectAsc13End: String = "</aspectAsc13>"
    let aspectMc13Start: String = "  <aspectMc13>"
    let aspectMc13End: String = "</aspectMc13>"
    let aspectEarth13Start: String = "  <aspectEarth13>"
    let aspectEarth13End: String = "</aspectEarth13>"
    let aspectLilith13Start: String = "  <aspectLilith13>"
    let aspectLilith13End: String = "</aspectLilith13>"
    let aspectSun23Start: String = "  <aspectSun23>"
    let aspectSun23End: String = "</aspectSun23>"
    let aspectMoon23Start: String = "  <aspectMoon23>"
    let aspectMoon23End: String = "</aspectMoon23>"
    let aspectMercury23Start: String = "  <aspectMercury23>"
    let aspectMercury23End: String = "</aspectMercury23>"
    let aspectVenus23Start: String = "  <aspectVenus23>"
    let aspectVenus23End: String = "</aspectVenus23>"
    let aspectMars23Start: String = "  <aspectMars23>"
    let aspectMars23End: String = "</aspectMars23>"
    let aspectJupiter23Start: String = "  <aspectJupiter23>"
    let aspectJupiter23End: String = "</aspectJupiter23>"
    let aspectSaturn23Start: String = "  <aspectSaturn23>"
    let aspectSaturn23End: String = "</aspectSaturn23>"
    let aspectUranus23Start: String = "  <aspectUranus23>"
    let aspectUranus23End: String = "</aspectUranus23>"
    let aspectNeptune23Start: String = "  <aspectNeptune23>"
    let aspectNeptune23End: String = "</aspectNeptune23>"
    let aspectPluto23Start: String = "  <aspectPluto23>"
    let aspectPluto23End: String = "</aspectPluto23>"
    let aspectDh23Start: String = "  <aspectDh23>"
    let aspectDh23End: String = "</aspectDh23>"
    let aspectChiron23Start: String = "  <aspectChiron23>"
    let aspectChiron23End: String = "</aspectChiron23>"
    let aspectAsc23Start: String = "  <aspectAsc23>"
    let aspectAsc23End: String = "</aspectAsc23>"
    let aspectMc23Start: String = "  <aspectMc23>"
    let aspectMc23End: String = "</aspectMc23>"
    let aspectEarth23Start: String = "  <aspectEarth23>"
    let aspectEarth23End: String = "</aspectEarth23>"
    let aspectLilith23Start: String = "  <aspectLilith23>"
    let aspectLilith23End: String = "</aspectLilith23>"
    let aspectConjunction11Start: String = "  <aspectConjunction11>"
    let aspectConjunction11End: String = "</aspectConjunction11>"
    let aspectOpposition11Start: String = "  <aspectOpposition11>"
    let aspectOpposition11End: String = "</aspectOpposition11>"
    let aspectTrine11Start: String = "  <aspectTrine11>"
    let aspectTrine11End: String = "</aspectTrine11>"
    let aspectSquare11Start: String = "  <aspectSquare11>"
    let aspectSquare11End: String = "</aspectSquare11>"
    let aspectSextile11Start: String = "  <aspectSextile11>"
    let aspectSextile11End: String = "</aspectSextile11>"
    let aspectInconjunct11Start: String = "  <aspectInconjunct11>"
    let aspectInconjunct11End: String = "</aspectInconjunct11>"
    let aspectSesquiquadrate11Start: String = "  <aspectSesquiquadrate11>"
    let aspectSesquiquadrate11End: String = "</aspectSesquiquadrate11>"
    let aspectConjunction22Start: String = "  <aspectConjunction22>"
    let aspectConjunction22End: String = "</aspectConjunction22>"
    let aspectOpposition22Start: String = "  <aspectOpposition22>"
    let aspectOpposition22End: String = "</aspectOpposition22>"
    let aspectTrine22Start: String = "  <aspectTrine22>"
    let aspectTrine22End: String = "</aspectTrine22>"
    let aspectSquare22Start: String = "  <aspectSquare22>"
    let aspectSquare22End: String = "</aspectSquare22>"
    let aspectSextile22Start: String = "  <aspectSextile22>"
    let aspectSextile22End: String = "</aspectSextile22>"
    let aspectInconjunct22Start: String = "  <aspectInconjunct22>"
    let aspectInconjunct22End: String = "</aspectInconjunct22>"
    let aspectSesquiquadrate22Start: String = "  <aspectSesquiquadrate22>"
    let aspectSesquiquadrate22End: String = "</aspectSesquiquadrate22>"
    let aspectConjunction33Start: String = "  <aspectConjunction33>"
    let aspectConjunction33End: String = "</aspectConjunction33>"
    let aspectOpposition33Start: String = "  <aspectOpposition33>"
    let aspectOpposition33End: String = "</aspectOpposition33>"
    let aspectTrine33Start: String = "  <aspectTrine33>"
    let aspectTrine33End: String = "</aspectTrine33>"
    let aspectSquare33Start: String = "  <aspectSquare33>"
    let aspectSquare33End: String = "</aspectSquare33>"
    let aspectSextile33Start: String = "  <aspectSextile33>"
    let aspectSextile33End: String = "</aspectSextile33>"
    let aspectInconjunct33Start: String = "  <aspectInconjunct33>"
    let aspectInconjunct33End: String = "</aspectInconjunct33>"
    let aspectSesquiquadrate33Start: String = "  <aspectSesquiquadrate33>"
    let aspectSesquiquadrate33End: String = "</aspectSesquiquadrate33>"
    let aspectConjunction12Start: String = "  <aspectConjunction12>"
    let aspectConjunction12End: String = "</aspectConjunction12>"
    let aspectOpposition12Start: String = "  <aspectOpposition12>"
    let aspectOpposition12End: String = "</aspectOpposition12>"
    let aspectTrine12Start: String = "  <aspectTrine12>"
    let aspectTrine12End: String = "</aspectTrine12>"
    let aspectSquare12Start: String = "  <aspectSquare12>"
    let aspectSquare12End: String = "</aspectSquare12>"
    let aspectSextile12Start: String = "  <aspectSextile12>"
    let aspectSextile12End: String = "</aspectSextile12>"
    let aspectInconjunct12Start: String = "  <aspectInconjunct12>"
    let aspectInconjunct12End: String = "</aspectInconjunct12>"
    let aspectSesquiquadrate12Start: String = "  <aspectSesquiquadrate12>"
    let aspectSesquiquadrate12End: String = "</aspectSesquiquadrate12>"
    let aspectConjunction13Start: String = "  <aspectConjunction13>"
    let aspectConjunction13End: String = "</aspectConjunction13>"
    let aspectOpposition13Start: String = "  <aspectOpposition13>"
    let aspectOpposition13End: String = "</aspectOpposition13>"
    let aspectTrine13Start: String = "  <aspectTrine13>"
    let aspectTrine13End: String = "</aspectTrine13>"
    let aspectSquare13Start: String = "  <aspectSquare13>"
    let aspectSquare13End: String = "</aspectSquare13>"
    let aspectSextile13Start: String = "  <aspectSextile13>"
    let aspectSextile13End: String = "</aspectSextile13>"
    let aspectInconjunct13Start: String = "  <aspectInconjunct13>"
    let aspectInconjunct13End: String = "</aspectInconjunct13>"
    let aspectSesquiquadrate13Start: String = "  <aspectSesquiquadrate13>"
    let aspectSesquiquadrate13End: String = "</aspectSesquiquadrate13>"
    let aspectConjunction23Start: String = "  <aspectConjunction23>"
    let aspectConjunction23End: String = "</aspectConjunction23>"
    let aspectOpposition23Start: String = "  <aspectOpposition23>"
    let aspectOpposition23End: String = "</aspectOpposition23>"
    let aspectTrine23Start: String = "  <aspectTrine23>"
    let aspectTrine23End: String = "</aspectTrine23>"
    let aspectSquare23Start: String = "  <aspectSquare23>"
    let aspectSquare23End: String = "</aspectSquare23>"
    let aspectSextile23Start: String = "  <aspectSextile23>"
    let aspectSextile23End: String = "</aspectSextile23>"
    let aspectInconjunct23Start: String = "  <aspectInconjunct23>"
    let aspectInconjunct23End: String = "</aspectInconjunct23>"
    let aspectSesquiquadrate23Start: String = "  <aspectSesquiquadrate23>"
    let aspectSesquiquadrate23End: String = "</aspectSesquiquadrate23>"

    func NewSetting() -> NSString {
        var text: String
        
        text = xmlhead
        text += "\n"
        text += xmltop
        text += "\n"
        text += dispnameStart
        text += "名称未設定"
        text += dispnameEnd
        text += "\n"
        text += orbSunSoft1st0Start
        text += "8"
        text += orbSunSoft1st0End
        text += "\n"
        text += orbSunSoft1st1Start
        text += "8"
        text += orbSunSoft1st1End
        text += "\n"
        text += orbSunSoft1st2Start
        text += "8"
        text += orbSunSoft1st2End
        text += "\n"
        text += orbSunSoft1st3Start
        text += "8"
        text += orbSunSoft1st3End
        text += "\n"
        text += orbSunSoft1st4Start
        text += "8"
        text += orbSunSoft1st4End
        text += "\n"
        text += orbSunSoft1st5Start
        text += "8"
        text += orbSunSoft1st5End
        text += "\n"
        text += orbSunHard1st0Start
        text += "4"
        text += orbSunHard1st0End
        text += "\n"
        text += orbSunHard1st1Start
        text += "4"
        text += orbSunHard1st1End
        text += "\n"
        text += orbSunHard1st2Start
        text += "4"
        text += orbSunHard1st2End
        text += "\n"
        text += orbSunHard1st3Start
        text += "4"
        text += orbSunHard1st3End
        text += "\n"
        text += orbSunHard1st4Start
        text += "4"
        text += orbSunHard1st4End
        text += "\n"
        text += orbSunHard1st5Start
        text += "4"
        text += orbSunHard1st5End
        text += "\n"
        text += orbMoonSoft1st0Start
        text += "8"
        text += orbMoonSoft1st0End
        text += "\n"
        text += orbMoonSoft1st1Start
        text += "8"
        text += orbMoonSoft1st1End
        text += "\n"
        text += orbMoonSoft1st2Start
        text += "8"
        text += orbMoonSoft1st2End
        text += "\n"
        text += orbMoonSoft1st3Start
        text += "8"
        text += orbMoonSoft1st3End
        text += "\n"
        text += orbMoonSoft1st4Start
        text += "8"
        text += orbMoonSoft1st4End
        text += "\n"
        text += orbMoonSoft1st5Start
        text += "8"
        text += orbMoonSoft1st5End
        text += "\n"
        text += orbMoonHard1st0Start
        text += "4"
        text += orbMoonHard1st0End
        text += "\n"
        text += orbMoonHard1st1Start
        text += "4"
        text += orbMoonHard1st1End
        text += "\n"
        text += orbMoonHard1st2Start
        text += "4"
        text += orbMoonHard1st2End
        text += "\n"
        text += orbMoonHard1st3Start
        text += "4"
        text += orbMoonHard1st3End
        text += "\n"
        text += orbMoonHard1st4Start
        text += "4"
        text += orbMoonHard1st4End
        text += "\n"
        text += orbMoonHard1st5Start
        text += "4"
        text += orbMoonHard1st5End
        text += "\n"
        text += orbOtherSoft1st0Start
        text += "6"
        text += orbOtherSoft1st0End
        text += "\n"
        text += orbOtherSoft1st1Start
        text += "6"
        text += orbOtherSoft1st1End
        text += "\n"
        text += orbOtherSoft1st2Start
        text += "6"
        text += orbOtherSoft1st2End
        text += "\n"
        text += orbOtherSoft1st3Start
        text += "6"
        text += orbOtherSoft1st3End
        text += "\n"
        text += orbOtherSoft1st4Start
        text += "6"
        text += orbOtherSoft1st4End
        text += "\n"
        text += orbOtherSoft1st5Start
        text += "6"
        text += orbOtherSoft1st5End
        text += "\n"
        text += orbOtherHard1st0Start
        text += "4"
        text += orbOtherHard1st0End
        text += "\n"
        text += orbOtherHard1st1Start
        text += "4"
        text += orbOtherHard1st1End
        text += "\n"
        text += orbOtherHard1st2Start
        text += "4"
        text += orbOtherHard1st2End
        text += "\n"
        text += orbOtherHard1st3Start
        text += "4"
        text += orbOtherHard1st3End
        text += "\n"
        text += orbOtherHard1st4Start
        text += "4"
        text += orbOtherHard1st4End
        text += "\n"
        text += orbOtherHard1st5Start
        text += "4"
        text += orbOtherHard1st5End
        text += "\n"
        text += orbSunSoft2nd0Start
        text += "2"
        text += orbSunSoft2nd0End
        text += "\n"
        text += orbSunSoft2nd1Start
        text += "2"
        text += orbSunSoft2nd1End
        text += "\n"
        text += orbSunSoft2nd2Start
        text += "2"
        text += orbSunSoft2nd2End
        text += "\n"
        text += orbSunSoft2nd3Start
        text += "2"
        text += orbSunSoft2nd3End
        text += "\n"
        text += orbSunSoft2nd4Start
        text += "2"
        text += orbSunSoft2nd4End
        text += "\n"
        text += orbSunSoft2nd5Start
        text += "2"
        text += orbSunSoft2nd5End
        text += "\n"
        text += orbSunHard2nd0Start
        text += "1"
        text += orbSunHard2nd0End
        text += "\n"
        text += orbSunHard2nd1Start
        text += "1"
        text += orbSunHard2nd1End
        text += "\n"
        text += orbSunHard2nd2Start
        text += "1"
        text += orbSunHard2nd2End
        text += "\n"
        text += orbSunHard2nd3Start
        text += "1"
        text += orbSunHard2nd3End
        text += "\n"
        text += orbSunHard2nd4Start
        text += "1"
        text += orbSunHard2nd4End
        text += "\n"
        text += orbSunHard2nd5Start
        text += "1"
        text += orbSunHard2nd5End
        text += "\n"
        text += orbMoonSoft2nd0Start
        text += "2"
        text += orbMoonSoft2nd0End
        text += "\n"
        text += orbMoonSoft2nd1Start
        text += "2"
        text += orbMoonSoft2nd1End
        text += "\n"
        text += orbMoonSoft2nd2Start
        text += "2"
        text += orbMoonSoft2nd2End
        text += "\n"
        text += orbMoonSoft2nd3Start
        text += "2"
        text += orbMoonSoft2nd3End
        text += "\n"
        text += orbMoonSoft2nd4Start
        text += "2"
        text += orbMoonSoft2nd4End
        text += "\n"
        text += orbMoonSoft2nd5Start
        text += "2"
        text += orbMoonSoft2nd5End
        text += "\n"
        text += orbMoonHard2nd0Start
        text += "1"
        text += orbMoonHard2nd0End
        text += "\n"
        text += orbMoonHard2nd1Start
        text += "1"
        text += orbMoonHard2nd1End
        text += "\n"
        text += orbMoonHard2nd2Start
        text += "1"
        text += orbMoonHard2nd2End
        text += "\n"
        text += orbMoonHard2nd3Start
        text += "1"
        text += orbMoonHard2nd3End
        text += "\n"
        text += orbMoonHard2nd4Start
        text += "1"
        text += orbMoonHard2nd4End
        text += "\n"
        text += orbMoonHard2nd5Start
        text += "1"
        text += orbMoonHard2nd5End
        text += "\n"
        text += orbOtherSoft2nd0Start
        text += "1.5"
        text += orbOtherSoft2nd0End
        text += "\n"
        text += orbOtherSoft2nd1Start
        text += "1.5"
        text += orbOtherSoft2nd1End
        text += "\n"
        text += orbOtherSoft2nd2Start
        text += "1.5"
        text += orbOtherSoft2nd2End
        text += "\n"
        text += orbOtherSoft2nd3Start
        text += "1.5"
        text += orbOtherSoft2nd3End
        text += "\n"
        text += orbOtherSoft2nd4Start
        text += "1.5"
        text += orbOtherSoft2nd4End
        text += "\n"
        text += orbOtherSoft2nd5Start
        text += "1.5"
        text += orbOtherSoft2nd5End
        text += "\n"
        text += orbOtherHard2nd0Start
        text += "1"
        text += orbOtherHard2nd0End
        text += "\n"
        text += orbOtherHard2nd1Start
        text += "1"
        text += orbOtherHard2nd1End
        text += "\n"
        text += orbOtherHard2nd2Start
        text += "1"
        text += orbOtherHard2nd2End
        text += "\n"
        text += orbOtherHard2nd3Start
        text += "1"
        text += orbOtherHard2nd3End
        text += "\n"
        text += orbOtherHard2nd4Start
        text += "1"
        text += orbOtherHard2nd4End
        text += "\n"
        text += orbOtherHard2nd5Start
        text += "1"
        text += orbOtherHard2nd5End
        text += "\n"
        text += orbSunSoft1500Start
        text += "3"
        text += orbSunSoft1500End
        text += "\n"
        text += orbSunSoft1501Start
        text += "3"
        text += orbSunSoft1501End
        text += "\n"
        text += orbSunSoft1502Start
        text += "3"
        text += orbSunSoft1502End
        text += "\n"
        text += orbSunSoft1503Start
        text += "3"
        text += orbSunSoft1503End
        text += "\n"
        text += orbSunSoft1504Start
        text += "3"
        text += orbSunSoft1504End
        text += "\n"
        text += orbSunSoft1505Start
        text += "3"
        text += orbSunSoft1505End
        text += "\n"
        text += orbSunHard1500Start
        text += "1.5"
        text += orbSunHard1500End
        text += "\n"
        text += orbSunHard1501Start
        text += "1.5"
        text += orbSunHard1501End
        text += "\n"
        text += orbSunHard1502Start
        text += "1.5"
        text += orbSunHard1502End
        text += "\n"
        text += orbSunHard1503Start
        text += "1.5"
        text += orbSunHard1503End
        text += "\n"
        text += orbSunHard1504Start
        text += "1.5"
        text += orbSunHard1504End
        text += "\n"
        text += orbSunHard1505Start
        text += "1.5"
        text += orbSunHard1505End
        text += "\n"
        text += orbMoonSoft1500Start
        text += "3"
        text += orbMoonSoft1500End
        text += "\n"
        text += orbMoonSoft1501Start
        text += "3"
        text += orbMoonSoft1501End
        text += "\n"
        text += orbMoonSoft1502Start
        text += "3"
        text += orbMoonSoft1502End
        text += "\n"
        text += orbMoonSoft1503Start
        text += "3"
        text += orbMoonSoft1503End
        text += "\n"
        text += orbMoonSoft1504Start
        text += "3"
        text += orbMoonSoft1504End
        text += "\n"
        text += orbMoonSoft1505Start
        text += "3"
        text += orbMoonSoft1505End
        text += "\n"
        text += orbMoonHard1500Start
        text += "1.5"
        text += orbMoonHard1500End
        text += "\n"
        text += orbMoonHard1501Start
        text += "1.5"
        text += orbMoonHard1501End
        text += "\n"
        text += orbMoonHard1502Start
        text += "1.5"
        text += orbMoonHard1502End
        text += "\n"
        text += orbMoonHard1503Start
        text += "1.5"
        text += orbMoonHard1503End
        text += "\n"
        text += orbMoonHard1504Start
        text += "1.5"
        text += orbMoonHard1504End
        text += "\n"
        text += orbMoonHard1505Start
        text += "1.5"
        text += orbMoonHard1505End
        text += "\n"
        text += orbOtherSoft1500Start
        text += "2"
        text += orbOtherSoft1500End
        text += "\n"
        text += orbOtherSoft1501Start
        text += "2"
        text += orbOtherSoft1501End
        text += "\n"
        text += orbOtherSoft1502Start
        text += "2"
        text += orbOtherSoft1502End
        text += "\n"
        text += orbOtherSoft1503Start
        text += "2"
        text += orbOtherSoft1503End
        text += "\n"
        text += orbOtherSoft1504Start
        text += "2"
        text += orbOtherSoft1504End
        text += "\n"
        text += orbOtherSoft1505Start
        text += "2"
        text += orbOtherSoft1505End
        text += "\n"
        text += orbOtherHard1500Start
        text += "1"
        text += orbOtherHard1500End
        text += "\n"
        text += orbOtherHard1501Start
        text += "1"
        text += orbOtherHard1501End
        text += "\n"
        text += orbOtherHard1502Start
        text += "1"
        text += orbOtherHard1502End
        text += "\n"
        text += orbOtherHard1503Start
        text += "1"
        text += orbOtherHard1503End
        text += "\n"
        text += orbOtherHard1504Start
        text += "1"
        text += orbOtherHard1504End
        text += "\n"
        text += orbOtherHard1505Start
        text += "1"
        text += orbOtherHard1505End
        text += "\n"
        text += dispcircle0Start
        text += "true"
        text += dispcircle0End
        text += "\n"
        text += dispcircle1Start
        text += "false"
        text += dispcircle1End
        text += "\n"
        text += dispcircle2Start
        text += "false"
        text += dispcircle2End
        text += "\n"
        text += dispcircle3Start
        text += "false"
        text += dispcircle3End
        text += "\n"
        text += dispcircle4Start
        text += "false"
        text += dispcircle4End
        text += "\n"
        text += dispcircle5Start
        text += "false"
        text += dispcircle5End
        text += "\n"
        text += dispplanetSun11Start
        text += "true"
        text += dispplanetSun11End
        text += "\n"
        text += dispplanetMoon11Start
        text += "true"
        text += dispplanetMoon11End
        text += "\n"
        text += dispplanetMercury11Start
        text += "true"
        text += dispplanetMercury11End
        text += "\n"
        text += dispplanetVenus11Start
        text += "true"
        text += dispplanetVenus11End
        text += "\n"
        text += dispplanetMars11Start
        text += "true"
        text += dispplanetMars11End
        text += "\n"
        text += dispplanetJupiter11Start
        text += "true"
        text += dispplanetJupiter11End
        text += "\n"
        text += dispplanetSaturn11Start
        text += "true"
        text += dispplanetSaturn11End
        text += "\n"
        text += dispplanetUranus11Start
        text += "true"
        text += dispplanetUranus11End
        text += "\n"
        text += dispplanetNeptune11Start
        text += "true"
        text += dispplanetNeptune11End
        text += "\n"
        text += dispplanetPluto11Start
        text += "true"
        text += dispplanetPluto11End
        text += "\n"
        text += dispplanetDh11Start
        text += "true"
        text += dispplanetDh11End
        text += "\n"
        text += dispplanetChiron11Start
        text += "true"
        text += dispplanetChiron11End
        text += "\n"
        text += dispplanetAsc11Start
        text += "true"
        text += dispplanetAsc11End
        text += "\n"
        text += dispplanetMc11Start
        text += "true"
        text += dispplanetMc11End
        text += "\n"
        text += dispplanetEarth11Start
        text += "false"
        text += dispplanetEarth11End
        text += "\n"
        text += dispplanetLilith11Start
        text += "false"
        text += dispplanetLilith11End
        text += "\n"
        text += dispplanetSun22Start
        text += "true"
        text += dispplanetSun22End
        text += "\n"
        text += dispplanetMoon22Start
        text += "true"
        text += dispplanetMoon22End
        text += "\n"
        text += dispplanetMercury22Start
        text += "true"
        text += dispplanetMercury22End
        text += "\n"
        text += dispplanetVenus22Start
        text += "true"
        text += dispplanetVenus22End
        text += "\n"
        text += dispplanetMars22Start
        text += "true"
        text += dispplanetMars22End
        text += "\n"
        text += dispplanetJupiter22Start
        text += "true"
        text += dispplanetJupiter22End
        text += "\n"
        text += dispplanetSaturn22Start
        text += "true"
        text += dispplanetSaturn22End
        text += "\n"
        text += dispplanetUranus22Start
        text += "true"
        text += dispplanetUranus22End
        text += "\n"
        text += dispplanetNeptune22Start
        text += "true"
        text += dispplanetNeptune22End
        text += "\n"
        text += dispplanetPluto22Start
        text += "true"
        text += dispplanetPluto22End
        text += "\n"
        text += dispplanetDh22Start
        text += "true"
        text += dispplanetDh22End
        text += "\n"
        text += dispplanetChiron22Start
        text += "true"
        text += dispplanetChiron22End
        text += "\n"
        text += dispplanetAsc22Start
        text += "true"
        text += dispplanetAsc22End
        text += "\n"
        text += dispplanetMc22Start
        text += "true"
        text += dispplanetMc22End
        text += "\n"
        text += dispplanetEarth22Start
        text += "false"
        text += dispplanetEarth22End
        text += "\n"
        text += dispplanetLilith22Start
        text += "false"
        text += dispplanetLilith22End
        text += "\n"
        text += dispplanetSun33Start
        text += "true"
        text += dispplanetSun33End
        text += "\n"
        text += dispplanetMoon33Start
        text += "true"
        text += dispplanetMoon33End
        text += "\n"
        text += dispplanetMercury33Start
        text += "true"
        text += dispplanetMercury33End
        text += "\n"
        text += dispplanetVenus33Start
        text += "true"
        text += dispplanetVenus33End
        text += "\n"
        text += dispplanetMars33Start
        text += "true"
        text += dispplanetMars33End
        text += "\n"
        text += dispplanetJupiter33Start
        text += "true"
        text += dispplanetJupiter33End
        text += "\n"
        text += dispplanetSaturn33Start
        text += "true"
        text += dispplanetSaturn33End
        text += "\n"
        text += dispplanetUranus33Start
        text += "true"
        text += dispplanetUranus33End
        text += "\n"
        text += dispplanetNeptune33Start
        text += "true"
        text += dispplanetNeptune33End
        text += "\n"
        text += dispplanetPluto33Start
        text += "true"
        text += dispplanetPluto33End
        text += "\n"
        text += dispplanetDh33Start
        text += "true"
        text += dispplanetDh33End
        text += "\n"
        text += dispplanetChiron33Start
        text += "true"
        text += dispplanetChiron33End
        text += "\n"
        text += dispplanetAsc33Start
        text += "true"
        text += dispplanetAsc33End
        text += "\n"
        text += dispplanetMc33Start
        text += "true"
        text += dispplanetMc33End
        text += "\n"
        text += dispplanetEarth33Start
        text += "false"
        text += dispplanetEarth33End
        text += "\n"
        text += dispplanetLilith33Start
        text += "false"
        text += dispplanetLilith33End
        text += "\n"
        text += dispplanetSun12Start
        text += "true"
        text += dispplanetSun12End
        text += "\n"
        text += dispplanetMoon12Start
        text += "true"
        text += dispplanetMoon12End
        text += "\n"
        text += dispplanetMercury12Start
        text += "true"
        text += dispplanetMercury12End
        text += "\n"
        text += dispplanetVenus12Start
        text += "true"
        text += dispplanetVenus12End
        text += "\n"
        text += dispplanetMars12Start
        text += "true"
        text += dispplanetMars12End
        text += "\n"
        text += dispplanetJupiter12Start
        text += "true"
        text += dispplanetJupiter12End
        text += "\n"
        text += dispplanetSaturn12Start
        text += "true"
        text += dispplanetSaturn12End
        text += "\n"
        text += dispplanetUranus12Start
        text += "true"
        text += dispplanetUranus12End
        text += "\n"
        text += dispplanetNeptune12Start
        text += "true"
        text += dispplanetNeptune12End
        text += "\n"
        text += dispplanetPluto12Start
        text += "true"
        text += dispplanetPluto12End
        text += "\n"
        text += dispplanetDh12Start
        text += "true"
        text += dispplanetDh12End
        text += "\n"
        text += dispplanetChiron12Start
        text += "true"
        text += dispplanetChiron12End
        text += "\n"
        text += dispplanetAsc12Start
        text += "true"
        text += dispplanetAsc12End
        text += "\n"
        text += dispplanetMc12Start
        text += "true"
        text += dispplanetMc12End
        text += "\n"
        text += dispplanetEarth12Start
        text += "false"
        text += dispplanetEarth12End
        text += "\n"
        text += dispplanetLilith12Start
        text += "false"
        text += dispplanetLilith12End
        text += "\n"
        text += dispplanetSun13Start
        text += "true"
        text += dispplanetSun13End
        text += "\n"
        text += dispplanetMoon13Start
        text += "true"
        text += dispplanetMoon13End
        text += "\n"
        text += dispplanetMercury13Start
        text += "true"
        text += dispplanetMercury13End
        text += "\n"
        text += dispplanetVenus13Start
        text += "true"
        text += dispplanetVenus13End
        text += "\n"
        text += dispplanetMars13Start
        text += "true"
        text += dispplanetMars13End
        text += "\n"
        text += dispplanetJupiter13Start
        text += "true"
        text += dispplanetJupiter13End
        text += "\n"
        text += dispplanetSaturn13Start
        text += "true"
        text += dispplanetSaturn13End
        text += "\n"
        text += dispplanetUranus13Start
        text += "true"
        text += dispplanetUranus13End
        text += "\n"
        text += dispplanetNeptune13Start
        text += "true"
        text += dispplanetNeptune13End
        text += "\n"
        text += dispplanetPluto13Start
        text += "true"
        text += dispplanetPluto13End
        text += "\n"
        text += dispplanetDh13Start
        text += "true"
        text += dispplanetDh13End
        text += "\n"
        text += dispplanetChiron13Start
        text += "true"
        text += dispplanetChiron13End
        text += "\n"
        text += dispplanetAsc13Start
        text += "true"
        text += dispplanetAsc13End
        text += "\n"
        text += dispplanetMc13Start
        text += "true"
        text += dispplanetMc13End
        text += "\n"
        text += dispplanetEarth13Start
        text += "false"
        text += dispplanetEarth13End
        text += "\n"
        text += dispplanetLilith13Start
        text += "false"
        text += dispplanetLilith13End
        text += "\n"
        text += dispplanetSun23Start
        text += "true"
        text += dispplanetSun23End
        text += "\n"
        text += dispplanetMoon23Start
        text += "true"
        text += dispplanetMoon23End
        text += "\n"
        text += dispplanetMercury23Start
        text += "true"
        text += dispplanetMercury23End
        text += "\n"
        text += dispplanetVenus23Start
        text += "true"
        text += dispplanetVenus23End
        text += "\n"
        text += dispplanetMars23Start
        text += "true"
        text += dispplanetMars23End
        text += "\n"
        text += dispplanetJupiter23Start
        text += "true"
        text += dispplanetJupiter23End
        text += "\n"
        text += dispplanetSaturn23Start
        text += "true"
        text += dispplanetSaturn23End
        text += "\n"
        text += dispplanetUranus23Start
        text += "true"
        text += dispplanetUranus23End
        text += "\n"
        text += dispplanetNeptune23Start
        text += "true"
        text += dispplanetNeptune23End
        text += "\n"
        text += dispplanetPluto23Start
        text += "true"
        text += dispplanetPluto23End
        text += "\n"
        text += dispplanetDh23Start
        text += "true"
        text += dispplanetDh23End
        text += "\n"
        text += dispplanetChiron23Start
        text += "true"
        text += dispplanetChiron23End
        text += "\n"
        text += dispplanetAsc23Start
        text += "true"
        text += dispplanetAsc23End
        text += "\n"
        text += dispplanetMc23Start
        text += "true"
        text += dispplanetMc23End
        text += "\n"
        text += dispplanetEarth23Start
        text += "false"
        text += dispplanetEarth23End
        text += "\n"
        text += dispplanetLilith23Start
        text += "false"
        text += dispplanetLilith23End
        text += "\n"
        text += dispaspect0Start
        text += "true"
        text += dispaspect0End
        text += "\n"
        text += dispaspect1Start
        text += "false"
        text += dispaspect1End
        text += "\n"
        text += dispaspect2Start
        text += "false"
        text += dispaspect2End
        text += "\n"
        text += dispaspect3Start
        text += "false"
        text += dispaspect3End
        text += "\n"
        text += dispaspect4Start
        text += "false"
        text += dispaspect4End
        text += "\n"
        text += dispaspect5Start
        text += "false"
        text += dispaspect5End
        text += "\n"
        text += aspectSun11Start
        text += "true"
        text += aspectSun11End
        text += "\n"
        text += aspectMoon11Start
        text += "true"
        text += aspectMoon11End
        text += "\n"
        text += aspectMercury11Start
        text += "true"
        text += aspectMercury11End
        text += "\n"
        text += aspectVenus11Start
        text += "true"
        text += aspectVenus11End
        text += "\n"
        text += aspectMars11Start
        text += "true"
        text += aspectMars11End
        text += "\n"
        text += aspectJupiter11Start
        text += "true"
        text += aspectJupiter11End
        text += "\n"
        text += aspectSaturn11Start
        text += "true"
        text += aspectSaturn11End
        text += "\n"
        text += aspectUranus11Start
        text += "true"
        text += aspectUranus11End
        text += "\n"
        text += aspectNeptune11Start
        text += "true"
        text += aspectNeptune11End
        text += "\n"
        text += aspectPluto11Start
        text += "true"
        text += aspectPluto11End
        text += "\n"
        text += aspectDh11Start
        text += "true"
        text += aspectDh11End
        text += "\n"
        text += aspectChiron11Start
        text += "true"
        text += aspectChiron11End
        text += "\n"
        text += aspectAsc11Start
        text += "true"
        text += aspectAsc11End
        text += "\n"
        text += aspectMc11Start
        text += "true"
        text += aspectMc11End
        text += "\n"
        text += aspectEarth11Start
        text += "false"
        text += aspectEarth11End
        text += "\n"
        text += aspectLilith11Start
        text += "false"
        text += aspectLilith11End
        text += "\n"
        text += aspectSun22Start
        text += "true"
        text += aspectSun22End
        text += "\n"
        text += aspectMoon22Start
        text += "true"
        text += aspectMoon22End
        text += "\n"
        text += aspectMercury22Start
        text += "true"
        text += aspectMercury22End
        text += "\n"
        text += aspectVenus22Start
        text += "true"
        text += aspectVenus22End
        text += "\n"
        text += aspectMars22Start
        text += "true"
        text += aspectMars22End
        text += "\n"
        text += aspectJupiter22Start
        text += "true"
        text += aspectJupiter22End
        text += "\n"
        text += aspectSaturn22Start
        text += "true"
        text += aspectSaturn22End
        text += "\n"
        text += aspectUranus22Start
        text += "true"
        text += aspectUranus22End
        text += "\n"
        text += aspectNeptune22Start
        text += "true"
        text += aspectNeptune22End
        text += "\n"
        text += aspectPluto22Start
        text += "true"
        text += aspectPluto22End
        text += "\n"
        text += aspectDh22Start
        text += "true"
        text += aspectDh22End
        text += "\n"
        text += aspectChiron22Start
        text += "true"
        text += aspectChiron22End
        text += "\n"
        text += aspectAsc22Start
        text += "true"
        text += aspectAsc22End
        text += "\n"
        text += aspectMc22Start
        text += "true"
        text += aspectMc22End
        text += "\n"
        text += aspectEarth22Start
        text += "false"
        text += aspectEarth22End
        text += "\n"
        text += aspectLilith22Start
        text += "false"
        text += aspectLilith22End
        text += "\n"
        text += aspectSun33Start
        text += "true"
        text += aspectSun33End
        text += "\n"
        text += aspectMoon33Start
        text += "true"
        text += aspectMoon33End
        text += "\n"
        text += aspectMercury33Start
        text += "true"
        text += aspectMercury33End
        text += "\n"
        text += aspectVenus33Start
        text += "true"
        text += aspectVenus33End
        text += "\n"
        text += aspectMars33Start
        text += "true"
        text += aspectMars33End
        text += "\n"
        text += aspectJupiter33Start
        text += "true"
        text += aspectJupiter33End
        text += "\n"
        text += aspectSaturn33Start
        text += "true"
        text += aspectSaturn33End
        text += "\n"
        text += aspectUranus33Start
        text += "true"
        text += aspectUranus33End
        text += "\n"
        text += aspectNeptune33Start
        text += "true"
        text += aspectNeptune33End
        text += "\n"
        text += aspectPluto33Start
        text += "true"
        text += aspectPluto33End
        text += "\n"
        text += aspectDh33Start
        text += "true"
        text += aspectDh33End
        text += "\n"
        text += aspectChiron33Start
        text += "true"
        text += aspectChiron33End
        text += "\n"
        text += aspectAsc33Start
        text += "true"
        text += aspectAsc33End
        text += "\n"
        text += aspectMc33Start
        text += "true"
        text += aspectMc33End
        text += "\n"
        text += aspectEarth33Start
        text += "false"
        text += aspectEarth33End
        text += "\n"
        text += aspectLilith33Start
        text += "false"
        text += aspectLilith33End
        text += "\n"
        text += aspectSun12Start
        text += "true"
        text += aspectSun12End
        text += "\n"
        text += aspectMoon12Start
        text += "true"
        text += aspectMoon12End
        text += "\n"
        text += aspectMercury12Start
        text += "true"
        text += aspectMercury12End
        text += "\n"
        text += aspectVenus12Start
        text += "true"
        text += aspectVenus12End
        text += "\n"
        text += aspectMars12Start
        text += "true"
        text += aspectMars12End
        text += "\n"
        text += aspectJupiter12Start
        text += "true"
        text += aspectJupiter12End
        text += "\n"
        text += aspectSaturn12Start
        text += "true"
        text += aspectSaturn12End
        text += "\n"
        text += aspectUranus12Start
        text += "true"
        text += aspectUranus12End
        text += "\n"
        text += aspectNeptune12Start
        text += "true"
        text += aspectNeptune12End
        text += "\n"
        text += aspectPluto12Start
        text += "true"
        text += aspectPluto12End
        text += "\n"
        text += aspectDh12Start
        text += "true"
        text += aspectDh12End
        text += "\n"
        text += aspectChiron12Start
        text += "true"
        text += aspectChiron12End
        text += "\n"
        text += aspectAsc12Start
        text += "true"
        text += aspectAsc12End
        text += "\n"
        text += aspectMc12Start
        text += "true"
        text += aspectMc12End
        text += "\n"
        text += aspectEarth12Start
        text += "false"
        text += aspectEarth12End
        text += "\n"
        text += aspectLilith12Start
        text += "false"
        text += aspectLilith12End
        text += "\n"
        text += aspectSun13Start
        text += "true"
        text += aspectSun13End
        text += "\n"
        text += aspectMoon13Start
        text += "true"
        text += aspectMoon13End
        text += "\n"
        text += aspectMercury13Start
        text += "true"
        text += aspectMercury13End
        text += "\n"
        text += aspectVenus13Start
        text += "true"
        text += aspectVenus13End
        text += "\n"
        text += aspectMars13Start
        text += "true"
        text += aspectMars13End
        text += "\n"
        text += aspectJupiter13Start
        text += "true"
        text += aspectJupiter13End
        text += "\n"
        text += aspectSaturn13Start
        text += "true"
        text += aspectSaturn13End
        text += "\n"
        text += aspectUranus13Start
        text += "true"
        text += aspectUranus13End
        text += "\n"
        text += aspectNeptune13Start
        text += "true"
        text += aspectNeptune13End
        text += "\n"
        text += aspectPluto13Start
        text += "true"
        text += aspectPluto13End
        text += "\n"
        text += aspectDh13Start
        text += "true"
        text += aspectDh13End
        text += "\n"
        text += aspectChiron13Start
        text += "true"
        text += aspectChiron13End
        text += "\n"
        text += aspectAsc13Start
        text += "true"
        text += aspectAsc13End
        text += "\n"
        text += aspectMc13Start
        text += "true"
        text += aspectMc13End
        text += "\n"
        text += aspectEarth13Start
        text += "false"
        text += aspectEarth13End
        text += "\n"
        text += aspectLilith13Start
        text += "false"
        text += aspectLilith13End
        text += "\n"
        text += aspectConjunction11Start
        text += "true"
        text += aspectConjunction11End
        text += "\n"
        text += aspectOpposition11Start
        text += "true"
        text += aspectOpposition11End
        text += "\n"
        text += aspectTrine11Start
        text += "true"
        text += aspectTrine11End
        text += "\n"
        text += aspectSquare11Start
        text += "true"
        text += aspectSquare11End
        text += "\n"
        text += aspectSextile11Start
        text += "true"
        text += aspectSextile11End
        text += "\n"
        text += aspectInconjunct11Start
        text += "true"
        text += aspectInconjunct11End
        text += "\n"
        text += aspectSesquiquadrate11Start
        text += "true"
        text += aspectSesquiquadrate11End
        text += "\n"
        text += aspectConjunction22Start
        text += "true"
        text += aspectConjunction22End
        text += "\n"
        text += aspectOpposition22Start
        text += "true"
        text += aspectOpposition22End
        text += "\n"
        text += aspectTrine22Start
        text += "true"
        text += aspectTrine22End
        text += "\n"
        text += aspectSquare22Start
        text += "true"
        text += aspectSquare22End
        text += "\n"
        text += aspectSextile22Start
        text += "true"
        text += aspectSextile22End
        text += "\n"
        text += aspectInconjunct22Start
        text += "true"
        text += aspectInconjunct22End
        text += "\n"
        text += aspectSesquiquadrate22Start
        text += "true"
        text += aspectSesquiquadrate22End
        text += "\n"
        text += aspectConjunction33Start
        text += "true"
        text += aspectConjunction33End
        text += "\n"
        text += aspectOpposition33Start
        text += "true"
        text += aspectOpposition33End
        text += "\n"
        text += aspectTrine33Start
        text += "true"
        text += aspectTrine33End
        text += "\n"
        text += aspectSquare33Start
        text += "true"
        text += aspectSquare33End
        text += "\n"
        text += aspectSextile33Start
        text += "true"
        text += aspectSextile33End
        text += "\n"
        text += aspectInconjunct33Start
        text += "true"
        text += aspectInconjunct33End
        text += "\n"
        text += aspectSesquiquadrate33Start
        text += "true"
        text += aspectSesquiquadrate33End
        text += "\n"
        text += aspectConjunction12Start
        text += "true"
        text += aspectConjunction12End
        text += "\n"
        text += aspectOpposition12Start
        text += "true"
        text += aspectOpposition12End
        text += "\n"
        text += aspectTrine12Start
        text += "true"
        text += aspectTrine12End
        text += "\n"
        text += aspectSquare12Start
        text += "true"
        text += aspectSquare12End
        text += "\n"
        text += aspectSextile12Start
        text += "true"
        text += aspectSextile12End
        text += "\n"
        text += aspectInconjunct12Start
        text += "true"
        text += aspectInconjunct12End
        text += "\n"
        text += aspectSesquiquadrate12Start
        text += "true"
        text += aspectSesquiquadrate12End
        text += "\n"
        text += aspectConjunction13Start
        text += "true"
        text += aspectConjunction13End
        text += "\n"
        text += aspectOpposition13Start
        text += "true"
        text += aspectOpposition13End
        text += "\n"
        text += aspectTrine13Start
        text += "true"
        text += aspectTrine13End
        text += "\n"
        text += aspectSquare13Start
        text += "true"
        text += aspectSquare13End
        text += "\n"
        text += aspectSextile13Start
        text += "true"
        text += aspectSextile13End
        text += "\n"
        text += aspectInconjunct13Start
        text += "true"
        text += aspectInconjunct13End
        text += "\n"
        text += aspectSesquiquadrate13Start
        text += "true"
        text += aspectSesquiquadrate13End
        text += "\n"
        text += aspectConjunction23Start
        text += "true"
        text += aspectConjunction23End
        text += "\n"
        text += aspectOpposition23Start
        text += "true"
        text += aspectOpposition23End
        text += "\n"
        text += aspectTrine23Start
        text += "true"
        text += aspectTrine23End
        text += "\n"
        text += aspectSquare23Start
        text += "true"
        text += aspectSquare23End
        text += "\n"
        text += aspectSextile23Start
        text += "true"
        text += aspectSextile23End
        text += "\n"
        text += aspectInconjunct23Start
        text += "true"
        text += aspectInconjunct23End
        text += "\n"
        text += aspectSesquiquadrate23Start
        text += "true"
        text += aspectSesquiquadrate23End
        text += "\n"
        
        
        text += xmlend
        text += "\n"
        
        return text as NSString
    }
}
