//
//  SettingParse.swift
//  microcosm-mac
//
//  Created by Yuji Ogata on 2016/10/09.
//  Copyright © 2016年 Yuji Ogata. All rights reserved.
//

import Cocoa

class SettingParse: NSObject {
    
    func getSetting(no: Int) -> SettingData {
        let documents = NSSearchPathForDirectoriesInDomains(
            .documentDirectory,
            .userDomainMask, true)[0]

        let settingName: String = "setting"
        let directoryName = "microcosm"
        let createPath = documents + "/" + directoryName + "/system"    // 作成するディレクトリ名を含んだフルパス
        let setting: SettingData = SettingData(no)
        let settingFile = settingName + (String)(no) + ".mcsm"
        let settingPath = NSURL(fileURLWithPath: createPath).appendingPathComponent(settingFile)

        let settingfileManager = FileManager.default
        var isDir : ObjCBool = false
        
        let common: CommonData = CommonData()
        
        if (!settingfileManager.fileExists(atPath: (createPath + "/" + settingFile), isDirectory: &isDir)) {
            var str: String = "dispname:名称未設定" + "\n"
            str += "orb_sun_soft_1st_0:8" + "\n"
            str += "orb_sun_soft_1st_1:8" + "\n"
            str += "orb_sun_soft_1st_2:8" + "\n"
            str += "orb_sun_soft_1st_3:8" + "\n"
            str += "orb_sun_soft_1st_4:8" + "\n"
            str += "orb_sun_soft_1st_5:8" + "\n"
            str += "orb_sun_hard_1st_0:4" + "\n"
            str += "orb_sun_hard_1st_1:4" + "\n"
            str += "orb_sun_hard_1st_2:4" + "\n"
            str += "orb_sun_hard_1st_3:4" + "\n"
            str += "orb_sun_hard_1st_4:4" + "\n"
            str += "orb_sun_hard_1st_5:4" + "\n"
            str += "orb_moon_soft_1st_0:8" + "\n"
            str += "orb_moon_soft_1st_1:8" + "\n"
            str += "orb_moon_soft_1st_2:8" + "\n"
            str += "orb_moon_soft_1st_3:8" + "\n"
            str += "orb_moon_soft_1st_4:8" + "\n"
            str += "orb_moon_soft_1st_5:8" + "\n"
            str += "orb_moon_hard_1st_0:4" + "\n"
            str += "orb_moon_hard_1st_1:4" + "\n"
            str += "orb_moon_hard_1st_2:4" + "\n"
            str += "orb_moon_hard_1st_3:4" + "\n"
            str += "orb_moon_hard_1st_4:4" + "\n"
            str += "orb_moon_hard_1st_5:4" + "\n"
            str += "orb_other_soft_1st_0:6" + "\n"
            str += "orb_other_soft_1st_1:6" + "\n"
            str += "orb_other_soft_1st_2:6" + "\n"
            str += "orb_other_soft_1st_3:6" + "\n"
            str += "orb_other_soft_1st_4:6" + "\n"
            str += "orb_other_soft_1st_5:6" + "\n"
            str += "orb_other_hard_1st_0:4" + "\n"
            str += "orb_other_hard_1st_1:4" + "\n"
            str += "orb_other_hard_1st_2:4" + "\n"
            str += "orb_other_hard_1st_3:4" + "\n"
            str += "orb_other_hard_1st_4:4" + "\n"
            str += "orb_other_hard_1st_5:4" + "\n"
            str += "orb_sun_soft_2nd_0:2" + "\n"
            str += "orb_sun_soft_2nd_1:2" + "\n"
            str += "orb_sun_soft_2nd_2:2" + "\n"
            str += "orb_sun_soft_2nd_3:2" + "\n"
            str += "orb_sun_soft_2nd_4:2" + "\n"
            str += "orb_sun_soft_2nd_5:2" + "\n"
            str += "orb_sun_hard_2nd_0:1" + "\n"
            str += "orb_sun_hard_2nd_1:1" + "\n"
            str += "orb_sun_hard_2nd_2:1" + "\n"
            str += "orb_sun_hard_2nd_3:1" + "\n"
            str += "orb_sun_hard_2nd_4:1" + "\n"
            str += "orb_sun_hard_2nd_5:1" + "\n"
            str += "orb_moon_soft_2nd_0:2" + "\n"
            str += "orb_moon_soft_2nd_1:2" + "\n"
            str += "orb_moon_soft_2nd_2:2" + "\n"
            str += "orb_moon_soft_2nd_3:2" + "\n"
            str += "orb_moon_soft_2nd_4:2" + "\n"
            str += "orb_moon_soft_2nd_5:2" + "\n"
            str += "orb_moon_hard_2nd_0:1" + "\n"
            str += "orb_moon_hard_2nd_1:1" + "\n"
            str += "orb_moon_hard_2nd_2:1" + "\n"
            str += "orb_moon_hard_2nd_3:1" + "\n"
            str += "orb_moon_hard_2nd_4:1" + "\n"
            str += "orb_moon_hard_2nd_5:1" + "\n"
            str += "orb_other_soft_2nd_0:1.5" + "\n"
            str += "orb_other_soft_2nd_1:1.5" + "\n"
            str += "orb_other_soft_2nd_2:1.5" + "\n"
            str += "orb_other_soft_2nd_3:1.5" + "\n"
            str += "orb_other_soft_2nd_4:1.5" + "\n"
            str += "orb_other_soft_2nd_5:1.5" + "\n"
            str += "orb_other_hard_2nd_0:1" + "\n"
            str += "orb_other_hard_2nd_1:1" + "\n"
            str += "orb_other_hard_2nd_2:1" + "\n"
            str += "orb_other_hard_2nd_3:1" + "\n"
            str += "orb_other_hard_2nd_4:1" + "\n"
            str += "orb_other_hard_2nd_5:1" + "\n"
            str += "orb_sun_soft_150_0:3" + "\n"
            str += "orb_sun_soft_150_1:3" + "\n"
            str += "orb_sun_soft_150_2:3" + "\n"
            str += "orb_sun_soft_150_3:3" + "\n"
            str += "orb_sun_soft_150_4:3" + "\n"
            str += "orb_sun_soft_150_5:3" + "\n"
            str += "orb_sun_hard_150_0:1.5" + "\n"
            str += "orb_sun_hard_150_1:1.5" + "\n"
            str += "orb_sun_hard_150_2:1.5" + "\n"
            str += "orb_sun_hard_150_3:1.5" + "\n"
            str += "orb_sun_hard_150_4:1.5" + "\n"
            str += "orb_sun_hard_150_5:1.5" + "\n"
            str += "orb_moon_soft_150_0:3" + "\n"
            str += "orb_moon_soft_150_1:3" + "\n"
            str += "orb_moon_soft_150_2:3" + "\n"
            str += "orb_moon_soft_150_3:3" + "\n"
            str += "orb_moon_soft_150_4:3" + "\n"
            str += "orb_moon_soft_150_5:3" + "\n"
            str += "orb_moon_hard_150_0:1.5" + "\n"
            str += "orb_moon_hard_150_1:1.5" + "\n"
            str += "orb_moon_hard_150_2:1.5" + "\n"
            str += "orb_moon_hard_150_3:1.5" + "\n"
            str += "orb_moon_hard_150_4:1.5" + "\n"
            str += "orb_moon_hard_150_5:1.5" + "\n"
            str += "orb_other_soft_150_0:2" + "\n"
            str += "orb_other_soft_150_1:2" + "\n"
            str += "orb_other_soft_150_2:2" + "\n"
            str += "orb_other_soft_150_3:2" + "\n"
            str += "orb_other_soft_150_4:2" + "\n"
            str += "orb_other_soft_150_5:2" + "\n"
            str += "orb_other_hard_150_0:1" + "\n"
            str += "orb_other_hard_150_1:1" + "\n"
            str += "orb_other_hard_150_2:1" + "\n"
            str += "orb_other_hard_150_3:1" + "\n"
            str += "orb_other_hard_150_4:1" + "\n"
            str += "orb_other_hard_150_5:1" + "\n"
            str += "dispCircle0:true" + "\n"
            str += "dispCircle1:false" + "\n"
            str += "dispCircle2:false" + "\n"
            str += "dispCircle3:false" + "\n"
            str += "dispCircle4:false" + "\n"
            str += "dispCircle5:false" + "\n"
            str += "dispPlanetSun11:true" + "\n"
            str += "dispPlanetMoon11:true" + "\n"
            str += "dispPlanetMercury11:true" + "\n"
            str += "dispPlanetVenus11:true" + "\n"
            str += "dispPlanetMars11:true" + "\n"
            str += "dispPlanetJupiter11:true" + "\n"
            str += "dispPlanetSaturn11:true" + "\n"
            str += "dispPlanetUranus11:true" + "\n"
            str += "dispPlanetNeptune11:true" + "\n"
            str += "dispPlanetPluto11:true" + "\n"
            str += "dispPlanetDh11:true" + "\n"
            str += "dispPlanetChiron11:true" + "\n"
            str += "dispPlanetAsc11:true" + "\n"
            str += "dispPlanetMc11:true" + "\n"
            str += "dispPlanetEarth11:false" + "\n"
            str += "dispPlanetLilith11:false" + "\n"
            str += "dispPlanetSun22:true" + "\n"
            str += "dispPlanetMoon22:true" + "\n"
            str += "dispPlanetMercury22:true" + "\n"
            str += "dispPlanetVenus22:true" + "\n"
            str += "dispPlanetMars22:true" + "\n"
            str += "dispPlanetJupiter22:true" + "\n"
            str += "dispPlanetSaturn22:true" + "\n"
            str += "dispPlanetUranus22:true" + "\n"
            str += "dispPlanetNeptune22:true" + "\n"
            str += "dispPlanetPluto22:true" + "\n"
            str += "dispPlanetDh22:true" + "\n"
            str += "dispPlanetChiron22:true" + "\n"
            str += "dispPlanetAsc22:true" + "\n"
            str += "dispPlanetMc22:true" + "\n"
            str += "dispPlanetEarth22:false" + "\n"
            str += "dispPlanetLilith22:false" + "\n"
            str += "dispPlanetSun33:true" + "\n"
            str += "dispPlanetMoon33:true" + "\n"
            str += "dispPlanetMercury33:true" + "\n"
            str += "dispPlanetVenus33:true" + "\n"
            str += "dispPlanetMars33:true" + "\n"
            str += "dispPlanetJupiter33:true" + "\n"
            str += "dispPlanetSaturn33:true" + "\n"
            str += "dispPlanetUranus33:true" + "\n"
            str += "dispPlanetNeptune33:true" + "\n"
            str += "dispPlanetPluto33:true" + "\n"
            str += "dispPlanetDh33:true" + "\n"
            str += "dispPlanetChiron33:true" + "\n"
            str += "dispPlanetAsc33:true" + "\n"
            str += "dispPlanetMc33:true" + "\n"
            str += "dispPlanetEarth33:false" + "\n"
            str += "dispPlanetLilith33:false" + "\n"
            str += "dispPlanetSun12:true" + "\n"
            str += "dispPlanetMoon12:true" + "\n"
            str += "dispPlanetMercury12:true" + "\n"
            str += "dispPlanetVenus12:true" + "\n"
            str += "dispPlanetMars12:true" + "\n"
            str += "dispPlanetJupiter12:true" + "\n"
            str += "dispPlanetSaturn12:true" + "\n"
            str += "dispPlanetUranus12:true" + "\n"
            str += "dispPlanetNeptune12:true" + "\n"
            str += "dispPlanetPluto12:true" + "\n"
            str += "dispPlanetDh12:true" + "\n"
            str += "dispPlanetChiron12:true" + "\n"
            str += "dispPlanetAsc12:true" + "\n"
            str += "dispPlanetMc12:true" + "\n"
            str += "dispPlanetEarth12:true" + "\n"
            str += "dispPlanetLilith12:false" + "\n"
            str += "dispPlanetSun13:true" + "\n"
            str += "dispPlanetMoon13:true" + "\n"
            str += "dispPlanetMercury13:true" + "\n"
            str += "dispPlanetVenus13:true" + "\n"
            str += "dispPlanetMars13:true" + "\n"
            str += "dispPlanetJupiter13:true" + "\n"
            str += "dispPlanetSaturn13:true" + "\n"
            str += "dispPlanetUranus13:true" + "\n"
            str += "dispPlanetNeptune13:true" + "\n"
            str += "dispPlanetPluto13:true" + "\n"
            str += "dispPlanetDh13:true" + "\n"
            str += "dispPlanetChiron13:true" + "\n"
            str += "dispPlanetAsc13:true" + "\n"
            str += "dispPlanetMc13:true" + "\n"
            str += "dispPlanetEarth13:true" + "\n"
            str += "dispPlanetLilith13:false" + "\n"
            str += "dispPlanetSun23:true" + "\n"
            str += "dispPlanetMoon23:true" + "\n"
            str += "dispPlanetMercury23:true" + "\n"
            str += "dispPlanetVenus23:true" + "\n"
            str += "dispPlanetMars23:true" + "\n"
            str += "dispPlanetJupiter23:true" + "\n"
            str += "dispPlanetSaturn23:true" + "\n"
            str += "dispPlanetUranus23:true" + "\n"
            str += "dispPlanetNeptune23:true" + "\n"
            str += "dispPlanetPluto23:true" + "\n"
            str += "dispPlanetDh23:true" + "\n"
            str += "dispPlanetChiron23:true" + "\n"
            str += "dispPlanetAsc23:true" + "\n"
            str += "dispPlanetMc23:true" + "\n"
            str += "dispPlanetEarth23:true" + "\n"
            str += "dispPlanetLilith23:false" + "\n"
            str += "dispAspect0:true" + "\n"
            str += "dispAspect1:false" + "\n"
            str += "dispAspect2:false" + "\n"
            str += "dispAspect3:true" + "\n"
            str += "dispAspect4:false" + "\n"
            str += "dispAspect5:false" + "\n"
            str += "aspectSun11:true" + "\n"
            str += "aspectMoon11:true" + "\n"
            str += "aspectMercury11:true" + "\n"
            str += "aspectVenus11:true" + "\n"
            str += "aspectMars11:true" + "\n"
            str += "aspectJupiter11:true" + "\n"
            str += "aspectSaturn11:true" + "\n"
            str += "aspectUranus11:true" + "\n"
            str += "aspectNeptune11:true" + "\n"
            str += "aspectPluto11:true" + "\n"
            str += "aspectDh11:true" + "\n"
            str += "aspectChiron11:true" + "\n"
            str += "aspectAsc11:true" + "\n"
            str += "aspectMc11:true" + "\n"
            str += "aspectEarth11:false" + "\n"
            str += "aspectLilith11:false" + "\n"
            str += "aspectSun22:true" + "\n"
            str += "aspectMoon22:true" + "\n"
            str += "aspectMercury22:true" + "\n"
            str += "aspectVenus22:true" + "\n"
            str += "aspectMars22:true" + "\n"
            str += "aspectJupiter22:true" + "\n"
            str += "aspectSaturn22:true" + "\n"
            str += "aspectUranus22:true" + "\n"
            str += "aspectNeptune22:true" + "\n"
            str += "aspectPluto22:true" + "\n"
            str += "aspectDh22:true" + "\n"
            str += "aspectChiron22:true" + "\n"
            str += "aspectAsc22:true" + "\n"
            str += "aspectMc22:true" + "\n"
            str += "aspectEarth22:false" + "\n"
            str += "aspectLilith22:false" + "\n"
            str += "aspectSun33:true" + "\n"
            str += "aspectMoon33:true" + "\n"
            str += "aspectMercury33:true" + "\n"
            str += "aspectVenus33:true" + "\n"
            str += "aspectMars33:true" + "\n"
            str += "aspectJupiter33:true" + "\n"
            str += "aspectSaturn33:true" + "\n"
            str += "aspectUranus33:true" + "\n"
            str += "aspectNeptune33:true" + "\n"
            str += "aspectPluto33:true" + "\n"
            str += "aspectDh33:true" + "\n"
            str += "aspectChiron33:true" + "\n"
            str += "aspectAsc33:true" + "\n"
            str += "aspectMc33:true" + "\n"
            str += "aspectEarth33:false" + "\n"
            str += "aspectLilith33:false" + "\n"
            str += "aspectSun12:true" + "\n"
            str += "aspectMoon12:true" + "\n"
            str += "aspectMercury12:true" + "\n"
            str += "aspectVenus12:true" + "\n"
            str += "aspectMars12:true" + "\n"
            str += "aspectJupiter12:true" + "\n"
            str += "aspectSaturn12:true" + "\n"
            str += "aspectUranus12:true" + "\n"
            str += "aspectNeptune12:true" + "\n"
            str += "aspectPluto12:true" + "\n"
            str += "aspectDh12:true" + "\n"
            str += "aspectChiron12:true" + "\n"
            str += "aspectAsc12:true" + "\n"
            str += "aspectMc12:true" + "\n"
            str += "aspectEarth12:false" + "\n"
            str += "aspectLilith12:false" + "\n"
            str += "aspectSun13:true" + "\n"
            str += "aspectMoon13:true" + "\n"
            str += "aspectMercury13:true" + "\n"
            str += "aspectVenus13:true" + "\n"
            str += "aspectMars13:true" + "\n"
            str += "aspectJupiter13:true" + "\n"
            str += "aspectSaturn13:true" + "\n"
            str += "aspectUranus13:true" + "\n"
            str += "aspectNeptune13:true" + "\n"
            str += "aspectPluto13:true" + "\n"
            str += "aspectDh13:true" + "\n"
            str += "aspectChiron13:true" + "\n"
            str += "aspectAsc13:true" + "\n"
            str += "aspectMc13:true" + "\n"
            str += "aspectEarth13:false" + "\n"
            str += "aspectLilith13:false" + "\n"
            str += "aspectSun23:true" + "\n"
            str += "aspectMoon23:true" + "\n"
            str += "aspectMercury23:true" + "\n"
            str += "aspectVenus23:true" + "\n"
            str += "aspectMars23:true" + "\n"
            str += "aspectJupiter23:true" + "\n"
            str += "aspectSaturn23:true" + "\n"
            str += "aspectUranus23:true" + "\n"
            str += "aspectNeptune23:true" + "\n"
            str += "aspectPluto23:true" + "\n"
            str += "aspectDh23:true" + "\n"
            str += "aspectChiron23:true" + "\n"
            str += "aspectAsc23:true" + "\n"
            str += "aspectMc23:true" + "\n"
            str += "aspectEarth23:false" + "\n"
            str += "aspectLilith23:false" + "\n"
            str += "aspectConjunction11:true" + "\n"
            str += "aspectOpposition11:true" + "\n"
            str += "aspectTrine11:true" + "\n"
            str += "aspectSquare11:true" + "\n"
            str += "aspectSextile11:true" + "\n"
            str += "aspectInconjunct11:true" + "\n"
            str += "aspectSesquiquadrate11:true" + "\n"
            str += "aspectConjunction22:true" + "\n"
            str += "aspectOpposition22:true" + "\n"
            str += "aspectTrine22:true" + "\n"
            str += "aspectSquare22:true" + "\n"
            str += "aspectSextile22:true" + "\n"
            str += "aspectInconjunct22:true" + "\n"
            str += "aspectSesquiquadrate22:true" + "\n"
            str += "aspectConjunction33:true" + "\n"
            str += "aspectOpposition33:true" + "\n"
            str += "aspectTrine33:true" + "\n"
            str += "aspectSquare33:true" + "\n"
            str += "aspectSextile33:true" + "\n"
            str += "aspectInconjunct33:true" + "\n"
            str += "aspectSesquiquadrate33:true" + "\n"
            str += "aspectConjunction12:true" + "\n"
            str += "aspectOpposition12:true" + "\n"
            str += "aspectTrine12:true" + "\n"
            str += "aspectSquare12:true" + "\n"
            str += "aspectSextile12:true" + "\n"
            str += "aspectInconjunct12:true" + "\n"
            str += "aspectSesquiquadrate12:true" + "\n"
            str += "aspectConjunction13:true" + "\n"
            str += "aspectOpposition13:true" + "\n"
            str += "aspectTrine13:true" + "\n"
            str += "aspectSquare13:true" + "\n"
            str += "aspectSextile13:true" + "\n"
            str += "aspectInconjunct13:true" + "\n"
            str += "aspectSesquiquadrate13:true" + "\n"
            str += "aspectConjunction23:true" + "\n"
            str += "aspectOpposition23:true" + "\n"
            str += "aspectTrine23:true" + "\n"
            str += "aspectSquare23:true" + "\n"
            str += "aspectSextile23:true" + "\n"
            str += "aspectInconjunct23:true" + "\n"
            str += "aspectSesquiquadrate23:true" + "\n"
            
            FileManager.default.createFile(atPath: (createPath + "/" + settingFile), contents: str.data(using: String.Encoding(rawValue: String.Encoding.utf8.rawValue)))
        }
        
        do {
            let text2 = try NSString(contentsOf: settingPath!, encoding: String.Encoding.utf8.rawValue)
            text2.enumerateLines{
                line, stop in
                var arr = line.components(separatedBy: ":")
                switch(arr[0]) {
                case "dispname":
                        setting.dispName = arr[1]
                        break
                case "orb_sun_soft_1st_0":
                    setting.orbs[0][common.SUN_SOFT_1ST] = (Double)(arr[1])!
                    break
                case "orb_sun_soft_1st_1":
                    setting.orbs[1][common.SUN_SOFT_1ST] = (Double)(arr[1])!
                    break
                case "orb_sun_soft_1st_2":
                    setting.orbs[2][common.SUN_SOFT_1ST] = (Double)(arr[1])!
                    break
                case "orb_sun_soft_1st_3":
                    setting.orbs[3][common.SUN_SOFT_1ST] = (Double)(arr[1])!
                    break
                case "orb_sun_soft_1st_4":
                    setting.orbs[4][common.SUN_SOFT_1ST] = (Double)(arr[1])!
                    break
                case "orb_sun_soft_1st_5":
                    setting.orbs[5][common.SUN_SOFT_1ST] = (Double)(arr[1])!
                    break
                default:
                    break
                }
            }
        } catch {
            let alert:NSAlert = NSAlert();
            alert.messageText = "エラー";
            alert.informativeText = "ファイルの読み込みに失敗しました。";
            alert.runModal();
            return setting
        }
        return setting
    }

}
